import type { ScienceGameMeta } from './types';

export const SCIENCE_CLASS6_GAMES: ScienceGameMeta[] = [
  {
    id: 'magnet-rescue',
    title: 'Magnet Rescue',
    curriculumChapter: 'Chapter 4 — Exploring Magnets',
    description: 'Recover scattered magnetic iron & steel parts in a damaged workshop using physical magnetic attraction and test like/unlike poles.',
    gameType: 'Physics Interaction & Magnetic Attraction',
    avatar: '🧲',
    badge: 'Magnetism Master',
    colors: 'from-red-500 via-rose-500 to-amber-500',
    difficulty: 'Easy',
    estimatedTime: '4–6 min',
    xpReward: 35,
    learningOutcomes: ['Magnetic vs non-magnetic materials', 'Magnetic attraction & repulsion poles', 'Material sorting'],
  },
  {
    id: 'water-world',
    title: 'Water World',
    curriculumChapter: 'Chapter 8 — A Journey through States of Water & Ch 7 — Temperature',
    description: 'Control heat, evaporation, cloud cooling, condensation, and rain collection across an interactive ecosystem with real temperature dials.',
    gameType: 'Ecosystem Simulation & State Transitions',
    avatar: '💧',
    badge: 'Hydrologist',
    colors: 'from-sky-500 via-cyan-500 to-blue-600',
    difficulty: 'Medium',
    estimatedTime: '5–8 min',
    xpReward: 40,
    learningOutcomes: ['States of water (Ice, Liquid, Vapour)', 'Evaporation & condensation mechanisms', 'Temperature regulation'],
  },
  {
    id: 'separation-factory',
    title: 'The Separation Factory',
    curriculumChapter: 'Chapter 9 — Methods of Separation & Ch 6 — Materials',
    description: 'Operate physical factory sieves, settling tanks, decanting vessels, and filter funnels to separate everyday mixtures.',
    gameType: 'Laboratory Mixture Separation Simulator',
    avatar: '🧪',
    badge: 'Separation Specialist',
    colors: 'from-emerald-500 via-teal-500 to-cyan-600',
    difficulty: 'Medium',
    estimatedTime: '5–8 min',
    xpReward: 40,
    learningOutcomes: ['Sieving for size differences', 'Sedimentation & decantation', 'Filtration of insoluble residues'],
  },
  {
    id: 'measure-move',
    title: 'Measure & Move Workshop',
    curriculumChapter: 'Chapter 5 — Measurement of Length and Motion',
    description: 'Pilot a precision science rover, lay calibrated track segments, and measure straight vs curved obstacle distances in standard SI units.',
    gameType: 'Measurement Puzzle & Distance Navigation',
    avatar: '📏',
    badge: 'Master Surveyor',
    colors: 'from-amber-500 via-yellow-500 to-orange-500',
    difficulty: 'Medium',
    estimatedTime: '4–6 min',
    xpReward: 35,
    learningOutcomes: ['Standard length measurement (metres/cm)', 'Straight vs curved path distances', 'Position & motion tracking'],
  },
  {
    id: 'life-explorer',
    title: 'Life Explorer',
    curriculumChapter: 'Chapter 2 — Diversity in Living World & Ch 10 — Living Creatures',
    description: 'Explore a vibrant 2D biodiversity biome (pond, forest, canopy) to scan living organisms and classify them on your field board.',
    gameType: 'Biodiversity Exploration & Habitat Classification',
    avatar: '🌿',
    badge: 'Field Biologist',
    colors: 'from-lime-500 via-green-500 to-emerald-600',
    difficulty: 'Medium',
    estimatedTime: '6–8 min',
    xpReward: 40,
    learningOutcomes: ['Organism diversity & habitats', 'Characteristics of living things', 'Ecological adaptations'],
  },
  {
    id: 'science-detective',
    title: 'Science Detective Lab',
    curriculumChapter: 'Chapter 1 — The Wonderful World of Science',
    description: 'Investigate mystery phenomena on the interactive workbench: melt ice on thermal pads, test conductivity, and record scientific evidence.',
    gameType: 'Scientific Observation & Evidence Collection',
    avatar: '🔍',
    badge: 'Chief Investigator',
    colors: 'from-purple-500 via-indigo-500 to-blue-600',
    difficulty: 'Easy',
    estimatedTime: '4–6 min',
    xpReward: 35,
    learningOutcomes: ['Scientific method & hypothesis testing', 'Observational evidence recording', 'Empirical deduction'],
  },
  {
    id: 'food-lab-rescue',
    title: 'Food Lab Rescue',
    curriculumChapter: 'Chapter 3 — Mindful Eating: A Path to a Healthy Body',
    description: 'Formulate balanced school meals (carbohydrates, proteins, fats, vitamins) and conduct virtual iodine starch & biuret protein reagent tests.',
    gameType: 'Nutritional Formulation & Chemical Reagent Testing',
    avatar: '🥗',
    badge: 'Nutritional Scientist',
    colors: 'from-orange-500 via-amber-500 to-rose-500',
    difficulty: 'Medium',
    estimatedTime: '5–7 min',
    xpReward: 40,
    learningOutcomes: ['Balanced diet components', 'Nutrient testing (Iodine for Starch, Biuret for Protein)', 'Healthy dietary planning'],
  },
  {
    id: 'space-mission',
    title: 'Space Mission: Beyond Earth',
    curriculumChapter: 'Chapter 12 — Beyond Earth',
    description: 'Pilot an orbital research spacecraft around Earth, orbit the cratered Moon, navigate celestial solar orbits, and dock at the orbital station.',
    gameType: 'Orbital Spaceflight & Celestial Observation',
    avatar: '🚀',
    badge: 'Orbital Astronaut',
    colors: 'from-indigo-600 via-violet-600 to-slate-900',
    difficulty: 'Challenging',
    estimatedTime: '6–9 min',
    xpReward: 45,
    learningOutcomes: ['Earth, Moon & Sun orbital dynamics', 'Space exploration & data collection', 'Orbital navigation'],
  },
];
