package com.acadevia.admin.enums;

public enum AuditAction {
    // School
    SCHOOL_CREATED, SCHOOL_UPDATED, SCHOOL_ACTIVATED, SCHOOL_DEACTIVATED, SCHOOL_VERIFIED,
    // User
    USER_ACTIVATED, USER_DEACTIVATED, USER_ROLE_CHANGED, USER_PASSWORD_RESET,
    BULK_STUDENTS_IMPORTED, BULK_TEACHERS_IMPORTED,
    // Content
    COURSE_APPROVED, COURSE_REJECTED, CONTENT_FLAGGED, CONTENT_UNFLAGGED,
    // Gamification
    XP_RULE_UPDATED, BADGE_CREATED, BADGE_UPDATED, BADGE_DEACTIVATED,
    STREAK_RULE_UPDATED, DIFFICULTY_RULE_UPDATED,
    // Platform
    FEATURE_FLAG_TOGGLED, SETTING_UPDATED, MAINTENANCE_MODE_TOGGLED,
    ANNOUNCEMENT_CREATED, ANNOUNCEMENT_DELETED,
    LEADERBOARD_RESET, BULK_NOTIFICATION_SENT,
    // System
    ADMIN_LOGIN, ADMIN_LOGOUT, DATA_EXPORTED
}
