package com.acadevia.admin.enums;

public enum RuleType {
    XP_QUIZ, XP_COURSE, XP_GAME, XP_STREAK, XP_VIDEO,
    XP_MULTIPLAYER, XP_CHALLENGE, XP_POPUP,
    BADGE_THRESHOLD, STREAK_MILESTONE,
    ADAPTIVE_ACCURACY, ADAPTIVE_WIN_RATE,
    WALLET_XP_RATIO
}
