import type { LucideIcon } from 'lucide-react';
import {
  Atom,
  Bot,
  BookOpen,
  Landmark,
  Rocket,
  Sparkles,
  Target,
  Zap,
  Compass,
  Flame,
  Shield,
  Activity,
  Globe,
  FlaskConical,
  Boxes,
  Dna,
  Layers,
  Radio,
  Binary,
  Workflow,
  Keyboard,
  TreePine,
  Waves,
  Pickaxe,
  Search,
  Crosshair,
  Gauge,
  Microscope,
  Scroll,
  Sun,
  MapPin,
  CircuitBoard,
  KeyRound,
  Hammer,
  Brain,
} from 'lucide-react';

export type GameDifficulty = 'easy' | 'medium' | 'hard';
export type GameGenre =
  | 'Arcade & Racing'
  | 'Simulation & Lab'
  | 'Strategy & Building'
  | 'Puzzle & Logic'
  | 'Adventure & Quest';

export type AcademicSubjectName =
  | 'Mathematics'
  | 'Science'
  | 'Physics'
  | 'Chemistry'
  | 'Biology'
  | 'English'
  | 'History'
  | 'Geography'
  | 'Computer Science'
  | 'Mind & Memory'
  | 'Detective & Logic';

export interface GameDefinition {
  id: string;
  title: string;
  description: string;
  subject: AcademicSubjectName;
  difficulty: GameDifficulty;
  classes: string;
  classGrades: number[];
  genre: GameGenre;
  xpReward: number;
  estimatedTime: string;
  rating: number;
  playersCount: number;
  icon: LucideIcon;
  colors: string;
  badgeEmoji?: string;
  tagline?: string;
  learning: string[];
  howToPlay: string[];
  stages: string[];
  controlsDescription?: string;
  thumbnail?: string;
}

export const GAME_CATALOG: GameDefinition[] = [
  /* ======================================================================== */
  /*  1. MATHEMATICS (5 Games)                                                */
  /* ======================================================================== */
  {
    id: 'number-kingdom',
    title: 'Number Kingdom',
    description: 'Unlock magical realms through number sense, place values, arithmetic operations, and fractions.',
    subject: 'Mathematics',
    difficulty: 'easy',
    classes: '1–5',
    classGrades: [1, 2, 3, 4, 5],
    genre: 'Adventure & Quest',
    xpReward: 150,
    estimatedTime: '10–15 min',
    rating: 5.0,
    playersCount: 64200,
    icon: Sparkles,
    colors: 'from-amber-400 via-orange-400 to-rose-500',
    badgeEmoji: '🏰',
    learning: ['Number sense & place value', 'Arithmetic operations', 'Fraction mastery', 'Mental pattern recognition'],
    howToPlay: ['Choose your class and animal companion.', 'Solve real mathematical obstacles to rebuild the kingdom.', 'Earn stars, gems, and unlocks.'],
    stages: ['Number Forest', 'Addition Village', 'Multiplication Mountain', 'Fraction Castle', 'Grand Kingdom'],
    controlsDescription: 'Mouse click / Touch tap to interact with bridges, potions, and kingdom buildings.',
  },
  {
    id: 'vedic-math-master',
    title: 'Vedic Math Rush',
    description: 'Calculate fast to survive! High-speed endless lane runner where mental calculation chooses your path.',
    subject: 'Mathematics',
    difficulty: 'medium',
    classes: '5–10',
    classGrades: [5, 6, 7, 8, 9, 10],
    genre: 'Arcade & Racing',
    xpReward: 200,
    estimatedTime: '8–12 min',
    rating: 4.9,
    playersCount: 52400,
    icon: Zap,
    colors: 'from-amber-500 via-orange-500 to-rose-600',
    badgeEmoji: '⚡',
    learning: ['Vedic mental multiplication', 'Fast squares & square roots', 'Nikhilam base arithmetic', 'Rapid left-to-right calculation'],
    howToPlay: ['Run down the 3-lane mathematical highway.', 'Calculate mental arithmetic fast and switch to the correct gate.', 'Build combo streaks to activate Turbo Nitro speed!'],
    stages: ['Multiplication Straight', 'Sutra Tunnel', 'Square Root Expressway', 'Grandmaster Speed Arena'],
    controlsDescription: 'Arrow Keys / A & D to switch lanes, or Touch swipe on mobile.',
  },
  {
    id: 'trigonometry-quest',
    title: 'Trigonometry Quest',
    description: 'Master sin, cos, tan, standard angles, and the unit circle through a seven-stage boss quest.',
    subject: 'Mathematics',
    difficulty: 'hard',
    classes: '9–12',
    classGrades: [9, 10, 11, 12],
    genre: 'Adventure & Quest',
    xpReward: 180,
    estimatedTime: '12–18 min',
    rating: 4.9,
    playersCount: 58400,
    icon: Target,
    colors: 'from-violet-600 via-indigo-500 to-cyan-400',
    badgeEmoji: '📐',
    learning: ['Trigonometric ratios (sin, cos, tan)', 'Standard radian & degree angles', 'Unit circle coordinate projection', 'Trigonometric identities'],
    howToPlay: ['Align the unit circle angles accurately to charge your beam.', 'Solve heights and distances to scale cliffs.', 'Defeat the Trigonometric Titan.'],
    stages: ['Ratios Ridge', 'Angle Valley', 'Unit Circle Citadel', 'Identity Keep', 'Titan Finale'],
    controlsDescription: 'Mouse drag on the interactive unit circle / On-screen angle selector.',
    thumbnail: '/assets/thumbnails/trigonometry.jpg',
  },
  {
    id: 'fraction-forge',
    title: 'Fraction Forge',
    description: 'Combine, simplify, and craft raw materials into complex machines using fraction operations and ratios.',
    subject: 'Mathematics',
    difficulty: 'medium',
    classes: '5–8',
    classGrades: [5, 6, 7, 8],
    genre: 'Strategy & Building',
    xpReward: 140,
    estimatedTime: '10–15 min',
    rating: 4.8,
    playersCount: 38200,
    icon: Boxes,
    colors: 'from-blue-600 via-indigo-500 to-purple-600',
    badgeEmoji: '⚒️',
    learning: ['Equivalent fractions', 'Addition & subtraction with unlike denominators', 'Mixed numbers & reciprocals', 'Scaling ratios'],
    howToPlay: ['Mix liquid and ore fractions to match metallurgical formulas.', 'Balance beam scales with equivalent fractional weights.', 'Forge legendary items.'],
    stages: ['Smelter Basin', 'Ratio Anvil', 'Equivalent Foundry', 'Master Forge'],
    controlsDescription: 'Drag-and-drop fraction ingots into crucible vessels.',
  },
  {
    id: 'coordinate-quest',
    title: 'Coordinate Quest: Vector Voyage',
    description: 'Navigate uncharted seas and treacherous obstacles using coordinate geometry, slopes, and vector velocity.',
    subject: 'Mathematics',
    difficulty: 'hard',
    classes: '8–12',
    classGrades: [8, 9, 10, 11, 12],
    genre: 'Puzzle & Logic',
    xpReward: 160,
    estimatedTime: '10–15 min',
    rating: 4.7,
    playersCount: 31500,
    icon: Compass,
    colors: 'from-emerald-600 via-teal-500 to-cyan-500',
    badgeEmoji: '🧭',
    learning: ['Cartesian coordinates (x, y)', 'Slope formula m = (y2 - y1)/(x2 - x1)', 'Distance & midpoint formulas', 'Vector displacement & magnitude'],
    howToPlay: ['Plot ship trajectories on the Cartesian grid.', 'Calculate optimal slopes to dodge whirlpools and coral reefs.', 'Reach treasure coordinates.'],
    stages: ['Archipelago Grid', 'Slope Shallows', 'Vector Vortex', 'Cartesian Abyss'],
    controlsDescription: 'Click to plot points, drag vectors, or enter coordinate coordinates.',
  },

  /* ======================================================================== */
  /*  2. SCIENCE (Integrated Classes 6–10)                                    */
  /* ======================================================================== */
  {
    id: 'science-lab',
    title: 'Science Lab: Curiosity Hub',
    description: 'Run safe virtual experiments across physics, chemistry, biology, and space exploration.',
    subject: 'Science',
    difficulty: 'medium',
    classes: '6–8',
    classGrades: [6, 7, 8],
    genre: 'Simulation & Lab',
    xpReward: 150,
    estimatedTime: '10–15 min',
    rating: 4.9,
    playersCount: 42600,
    icon: Atom,
    colors: 'from-cyan-500 via-teal-500 to-emerald-500',
    badgeEmoji: '🔬',
    learning: ['Magnetic attraction & poles', 'States of water & evaporation', 'Mixture separation techniques', 'Orbital dynamics & gravity'],
    howToPlay: ['Select an experiment station from the Curiosity Hub.', 'Manipulate physical instruments and record observations.', 'Earn science credentials.'],
    stages: ['Magnet Rescue', 'Water World', 'Separation Factory', 'Measure & Move', 'Life Explorer', 'Space Mission'],
    controlsDescription: 'Interactive mouse drag-and-drop apparatus and sliders.',
  },
  {
    id: 'ecosystem-tycoon',
    title: 'Ecosystem Tycoon: Food Web Balance',
    description: 'Build and sustain living biomes by balancing producers, herbivores, predators, and decomposers.',
    subject: 'Science',
    difficulty: 'medium',
    classes: '6–10',
    classGrades: [6, 7, 8, 9, 10],
    genre: 'Simulation & Lab',
    xpReward: 150,
    estimatedTime: '12–16 min',
    rating: 4.8,
    playersCount: 36800,
    icon: TreePine,
    colors: 'from-emerald-500 via-green-600 to-lime-600',
    badgeEmoji: '🌿',
    learning: ['Trophic levels & energy transfer', 'Food chains and complex webs', 'Carrying capacity & population curves', 'Biodiversity stability'],
    howToPlay: ['Introduce flora and fauna into your biome sandbox.', 'Monitor the ecological balance gauge as seasons and droughts occur.', 'Prevent ecological collapse.'],
    stages: ['Pond Oasis', 'Grassland Savannah', 'Rainforest Canopy', 'Biosphere Prime'],
    controlsDescription: 'Click to introduce species, adjust environmental factors with sliders.',
  },
  {
    id: 'energy-transformer',
    title: 'Energy Transformer',
    description: 'Construct Rube Goldberg-style physics machines to convert kinetic, potential, thermal, and electrical energy.',
    subject: 'Science',
    difficulty: 'medium',
    classes: '6–10',
    classGrades: [6, 7, 8, 9, 10],
    genre: 'Puzzle & Logic',
    xpReward: 140,
    estimatedTime: '10–15 min',
    rating: 4.7,
    playersCount: 29400,
    icon: Flame,
    colors: 'from-amber-500 via-orange-500 to-yellow-400',
    badgeEmoji: '⚙️',
    learning: ['Law of conservation of energy', 'Potential vs Kinetic energy', 'Thermal & electrical conversion', 'Energy efficiency & friction loss'],
    howToPlay: ['Place ramps, turbines, boilers, and dynamos onto the circuit board.', 'Trigger the chain reaction to power the final lightbulb.', 'Maximize efficiency.'],
    stages: ['Gravity Chute', 'Steam Dynamo', 'Hydroelectric Dam', 'Fusion Reactor'],
    controlsDescription: 'Drag-and-drop machine components into grid slots, click Start.',
  },
  {
    id: 'optics-ray-maze',
    title: 'Optics Ray Maze',
    description: 'Direct laser beams through intricate optical chambers using mirrors, convex/concave lenses, and prisms.',
    subject: 'Science',
    difficulty: 'hard',
    classes: '7–10',
    classGrades: [7, 8, 9, 10],
    genre: 'Puzzle & Logic',
    xpReward: 160,
    estimatedTime: '10–14 min',
    rating: 4.8,
    playersCount: 34100,
    icon: Crosshair,
    colors: 'from-pink-500 via-rose-500 to-yellow-400',
    badgeEmoji: '🔦',
    learning: ['Laws of reflection (angle i = angle r)', 'Refraction & Snell’s Law', 'Total internal reflection', 'Dispersion of white light through prisms'],
    howToPlay: ['Position flat and curved mirrors to reflect photons.', 'Use lenses to converge or diverge rays onto target light receptors.', 'Avoid black holes.'],
    stages: ['Plane Mirror Chamber', 'Refraction Vault', 'Prism Spectrum', 'Laser Matrix'],
    controlsDescription: 'Click and rotate mirrors and optical lenses to aim the light beam.',
  },
  {
    id: 'plate-tectonics-lab',
    title: 'Plate Tectonics: Earth Shaker',
    description: 'Simulate continental drift, fault lines, volcanic eruptions, and seismic P & S waves across tectonic plates.',
    subject: 'Science',
    difficulty: 'medium',
    classes: '6–9',
    classGrades: [6, 7, 8, 9],
    genre: 'Simulation & Lab',
    xpReward: 130,
    estimatedTime: '8–12 min',
    rating: 4.6,
    playersCount: 26500,
    icon: Layers,
    colors: 'from-stone-600 via-amber-700 to-orange-600',
    badgeEmoji: '🌋',
    learning: ['Convergent, divergent & transform boundaries', 'Subduction zones & mountain formation', 'Seismic wave velocity (P-waves vs S-waves)', 'Epicentre triangulation'],
    howToPlay: ['Push and pull tectonic plates to observe crustal deformations.', 'Triangulate seismograph readings to locate the earthquake epicenter.', 'Trigger volcanic pressure releases.'],
    stages: ['Rift Valley', 'Subduction Trench', 'Ring of Fire', 'Pangea Assembly'],
    controlsDescription: 'Click and drag tectonic boundary handles, read seismograph monitors.',
  },

  /* ======================================================================== */
  /*  3. PHYSICS (Classes 9–12)                                               */
  /* ======================================================================== */
  {
    id: 'projectile-master',
    title: 'Projectile Master: Ballistics Lab',
    description: 'Master kinematic equations by calculating launch angles, muzzle velocities, and trajectory parabolas.',
    subject: 'Physics',
    difficulty: 'medium',
    classes: '9–12',
    classGrades: [9, 10, 11, 12],
    genre: 'Simulation & Lab',
    xpReward: 170,
    estimatedTime: '10–15 min',
    rating: 4.9,
    playersCount: 47200,
    icon: Target,
    colors: 'from-blue-600 via-indigo-600 to-cyan-500',
    badgeEmoji: '🎯',
    learning: ['Kinematic motion equations', 'Range R = (v^2 * sin(2θ)) / g', 'Maximum height H = (v^2 * sin^2(θ)) / 2g', 'Effects of air resistance & gravity variation'],
    howToPlay: ['Adjust your cannon angle θ and initial velocity v.', 'Factor in planetary gravity (Earth, Moon, Mars).', 'Hit targets through wind shears and obstacles.'],
    stages: ['Target Range', 'Canyon Crossing', 'Lunar Artillery', 'Martian Storm'],
    controlsDescription: 'Sliders or input fields for launch angle and velocity; fire button.',
  },
  {
    id: 'circuit-runner',
    title: 'Circuit Runner: Electric Grid',
    description: 'Design and repair functional circuits using Ohm’s law, series/parallel branches, and logic switches.',
    subject: 'Physics',
    difficulty: 'medium',
    classes: '8–12',
    classGrades: [8, 9, 10, 11, 12],
    genre: 'Puzzle & Logic',
    xpReward: 160,
    estimatedTime: '10–14 min',
    rating: 4.8,
    playersCount: 39500,
    icon: CircuitBoard,
    colors: 'from-amber-400 via-yellow-500 to-orange-500',
    badgeEmoji: '💡',
    learning: ['Ohm’s law (V = I * R)', 'Equivalent resistance in series and parallel', 'Kirchhoff’s current and voltage laws', 'Capacitors and short-circuit prevention'],
    howToPlay: ['Wire resistors, bulbs, and batteries to meet target voltage and current.', 'Balance branches to prevent blown fuses.', 'Power up the research lab.'],
    stages: ['Breadboard Basics', 'Parallel Junction', 'Wheatstone Bridge', 'Power Grid Core'],
    controlsDescription: 'Click nodes to draw wire paths and drop electrical components.',
  },
  {
    id: 'truss-bridge-builder',
    title: 'Truss & Bridge Builder',
    description: 'Engineer load-bearing bridges and trusses while analyzing tension, compression, and shear forces.',
    subject: 'Physics',
    difficulty: 'hard',
    classes: '9–12',
    classGrades: [9, 10, 11, 12],
    genre: 'Strategy & Building',
    xpReward: 180,
    estimatedTime: '12–18 min',
    rating: 4.9,
    playersCount: 35100,
    icon: Hammer,
    colors: 'from-orange-600 via-amber-600 to-stone-700',
    badgeEmoji: '🌉',
    learning: ['Static equilibrium (ΣF = 0, Στ = 0)', 'Tension vs compression in members', 'Triangulation truss stability', 'Young’s modulus and material yield strength'],
    howToPlay: ['Draw structural members between pin joints within budget.', 'Initiate the heavy truck load test.', 'Identify stress points (red/blue heatmaps) and reinforce them.'],
    stages: ['River Crossing', 'Railway Gorge', 'Suspension Bay', 'Mega Viaduct'],
    controlsDescription: 'Click and drag joints to build beams, click Test to simulate physics load.',
  },
  {
    id: 'physics-velocity-racer',
    title: 'Velocity Racer: Newton’s Track',
    description: 'Drive an interactive physics vehicle where friction coefficients, banking angles, and momentum dictate grip.',
    subject: 'Physics',
    difficulty: 'medium',
    classes: '8–11',
    classGrades: [8, 9, 10, 11],
    genre: 'Arcade & Racing',
    xpReward: 150,
    estimatedTime: '8–12 min',
    rating: 4.7,
    playersCount: 33800,
    icon: Gauge,
    colors: 'from-red-500 via-rose-600 to-amber-500',
    badgeEmoji: '🏎️',
    learning: ['Newton’s second law (F = ma)', 'Static and kinetic friction', 'Centripetal force on banked curves', 'Stopping distance and momentum'],
    howToPlay: ['Tune vehicle mass, tire friction, and aerodynamic downforce.', 'Accelerate along the track and feather the throttle around hairpin bends.', 'Win the Grand Prix.'],
    stages: ['Asphalt Sprint', 'Wet Weather Chicane', 'Banked Velodrome', 'Ice Ring Challenge'],
    controlsDescription: 'Arrow keys / WASD to steer and throttle.',
  },
  {
    id: 'gravity-orbit-lab',
    title: 'Gravity & Orbit Lab',
    description: 'Simulate celestial mechanics, slingshot maneuvers, and stable orbits around planets using universal gravitation.',
    subject: 'Physics',
    difficulty: 'hard',
    classes: '9–12',
    classGrades: [9, 10, 11, 12],
    genre: 'Simulation & Lab',
    xpReward: 190,
    estimatedTime: '12–16 min',
    rating: 4.9,
    playersCount: 31200,
    icon: Rocket,
    colors: 'from-indigo-700 via-purple-700 to-slate-900',
    badgeEmoji: '🪐',
    learning: ['Newton’s law of universal gravitation', 'Orbital speed v = √(GM/r)', 'Kepler’s laws of planetary motion', 'Gravitational slingshot maneuvers'],
    howToPlay: ['Launch probes by setting initial velocity vectors.', 'Execute gravity-assist slingshots around massive planets.', 'Achieve stable geostationary orbit.'],
    stages: ['Low Earth Orbit', 'Lunar Transfer Orbit', 'Jupiter Slingshot', 'Interstellar Escape'],
    controlsDescription: 'Click and drag launch vectors, toggle trajectory prediction paths.',
    thumbnail: '/assets/thumbnails/physics.jpg',
  },

  /* ======================================================================== */
  /*  4. CHEMISTRY (Classes 9–12)                                             */
  /* ======================================================================== */
  {
    id: 'element-factory',
    title: 'Element Factory: Periodic Clash',
    description: 'Strategic card battle driven by periodic trends, electronegativity, valence electrons, and ionization energies.',
    subject: 'Chemistry',
    difficulty: 'medium',
    classes: '9–12',
    classGrades: [9, 10, 11, 12],
    genre: 'Strategy & Building',
    xpReward: 160,
    estimatedTime: '10–15 min',
    rating: 4.8,
    playersCount: 38700,
    icon: FlaskConical,
    colors: 'from-emerald-500 via-teal-600 to-cyan-600',
    badgeEmoji: '🧪',
    learning: ['Periodic table groups and periods', 'Valence electron configurations', 'Electronegativity and reactivity trends', 'Noble gas octet stability'],
    howToPlay: ['Deploy element cards with matching valence electron configurations.', 'Trigger displacement reactions against opponent elements.', 'Form stable salts to win.'],
    stages: ['Alkali Foothills', 'Halogen Arena', 'Transition Metal Keep', 'Noble Gas Sanctum'],
    controlsDescription: 'Card selection and drag onto active battle chemical slots.',
  },
  {
    id: 'molecule-crafter',
    title: 'Molecule Crafter: 3D Bond Builder',
    description: 'Synthesize organic and inorganic molecules by snapping atoms together according to covalent valencies and VSEPR geometry.',
    subject: 'Chemistry',
    difficulty: 'hard',
    classes: '9–12',
    classGrades: [9, 10, 11, 12],
    genre: 'Puzzle & Logic',
    xpReward: 170,
    estimatedTime: '12–16 min',
    rating: 4.9,
    playersCount: 34500,
    icon: Atom,
    colors: 'from-violet-600 via-purple-600 to-indigo-700',
    badgeEmoji: '🧬',
    learning: ['Covalent, ionic & hydrogen bonding', 'Lewis octet & duet rules', 'VSEPR molecular geometries (linear, tetrahedral, etc.)', 'Polarity and bond angles'],
    howToPlay: ['Select carbon, hydrogen, oxygen, and nitrogen atoms from the rack.', 'Create single, double, and triple bonds to satisfy valencies.', 'Synthesize target compounds.'],
    stages: ['Hydrocarbon Alley', 'Alcohol & Ester Chamber', 'Aromatic Ring', 'Macromolecule Synthesis'],
    controlsDescription: 'Click and drag bond connectors between atoms; rotate 3D view.',
  },
  {
    id: 'reaction-reactor',
    title: 'Reaction Reactor: Stoichiometry Balance',
    description: 'Balance chemical equations in rapid real-time to prevent runaway thermal reactions and maximize chemical yield.',
    subject: 'Chemistry',
    difficulty: 'medium',
    classes: '8–11',
    classGrades: [8, 9, 10, 11],
    genre: 'Arcade & Racing',
    xpReward: 150,
    estimatedTime: '8–12 min',
    rating: 4.7,
    playersCount: 41200,
    icon: Flame,
    colors: 'from-orange-500 via-amber-500 to-red-600',
    badgeEmoji: '⚗️',
    learning: ['Law of conservation of mass', 'Balancing stoichiometric coefficients', 'Limiting and excess reactants', 'Exothermic vs endothermic energy profiles'],
    howToPlay: ['Adjust reactant and product stoichiometric coefficients.', 'Ensure atom counts match on both sides before the reactor pressure gauge spikes.', 'Produce vital compounds.'],
    stages: ['Combustion Line', 'Neutralization Tank', 'Precipitation Chamber', 'Industrial Haber Process'],
    controlsDescription: 'Click stepper buttons (+/-) to change chemical coefficients.',
  },
  {
    id: 'acid-base-titration',
    title: 'Acid-Base Titration Master',
    description: 'Perform high-precision laboratory titrations, control dropwise burette flow, and hit the neutralization equivalence point.',
    subject: 'Chemistry',
    difficulty: 'hard',
    classes: '10–12',
    classGrades: [10, 11, 12],
    genre: 'Simulation & Lab',
    xpReward: 180,
    estimatedTime: '10–15 min',
    rating: 4.8,
    playersCount: 29800,
    icon: FlaskConical,
    colors: 'from-fuchsia-600 via-pink-600 to-rose-500',
    badgeEmoji: '💧',
    learning: ['pH scale (0–14) and logarithmic concentrations', 'Molarity (M1V1 = M2V2)', 'Indicator color transitions (phenolphthalein, methyl orange)', 'Strong vs weak acid-base titration curves'],
    howToPlay: ['Open the burette valve to add titrant into the analyte flask.', 'Switch to single-drop mode near the predicted endpoint.', 'Stop right at the color change.'],
    stages: ['HCl vs NaOH Standard', 'Vinegar Acetic Acid Assay', 'Weak Acid Buffer Curve', 'Polyprotic Challenge'],
    controlsDescription: 'Stopcock flow slider and single-drop dispensing button.',
  },
  {
    id: 'states-of-matter-lab',
    title: 'States of Matter: Thermal Kinetic Lab',
    description: 'Manipulate temperature and pressure to observe particle Brownian motion, latent heat, and phase transitions.',
    subject: 'Chemistry',
    difficulty: 'easy',
    classes: '6–9',
    classGrades: [6, 7, 8, 9],
    genre: 'Simulation & Lab',
    xpReward: 120,
    estimatedTime: '8–12 min',
    rating: 4.6,
    playersCount: 27900,
    icon: Waves,
    colors: 'from-sky-400 via-blue-500 to-indigo-600',
    badgeEmoji: '🧊',
    learning: ['Solid, liquid, and gas kinetic theory', 'Melting, boiling, condensation, sublimation', 'Boyle’s and Charles’s gas laws', 'Intermolecular forces vs kinetic energy'],
    howToPlay: ['Heat or cool the sealed container with burner controls.', 'Compress the piston to inspect pressure increases.', 'Observe particles bouncing in real time.'],
    stages: ['Ice to Steam', 'Liquid Nitrogen Cold', 'Aerosol Compression', 'Plasma State'],
    controlsDescription: 'Heater/cooler flame slider, piston compressor lever.',
  },

  /* ======================================================================== */
  /*  5. BIOLOGY (Classes 8–12)                                               */
  /* ======================================================================== */
  {
    id: 'cell-defender',
    title: 'Cell Defender: Immune Assault',
    description: 'Protect a eukaryotic cell from pathogenic viruses and bacteria by mobilizing organelles, antibodies, and macrophages.',
    subject: 'Biology',
    difficulty: 'medium',
    classes: '8–12',
    classGrades: [8, 9, 10, 11, 12],
    genre: 'Strategy & Building',
    xpReward: 170,
    estimatedTime: '10–15 min',
    rating: 4.9,
    playersCount: 46100,
    icon: Shield,
    colors: 'from-teal-500 via-emerald-600 to-cyan-600',
    badgeEmoji: '🛡️',
    learning: ['Cell organelles (mitochondria, ribosomes, Golgi, lysosomes)', 'Cell membrane selective permeability', 'Innate vs adaptive immune response', 'Antibody-antigen specificity'],
    howToPlay: ['Deploy ribosomes to synthesize defense proteins.', 'Deploy lysosomes to digest engulf pathogens.', 'Trigger macrophage phagocytosis against viral waves.'],
    stages: ['Membrane Breach', 'Cytoplasm Infiltration', 'Nuclear Vault Defense', 'Systemic Immunity'],
    controlsDescription: 'Click to build organelle defense towers on cellular grid sites.',
  },
  {
    id: 'dna-helix-builder',
    title: 'DNA Helix Builder: The Genetic Code',
    description: 'Assemble complementary DNA strands, transcribe mRNA codons, and translate proteins on the ribosome.',
    subject: 'Biology',
    difficulty: 'hard',
    classes: '9–12',
    classGrades: [9, 10, 11, 12],
    genre: 'Puzzle & Logic',
    xpReward: 180,
    estimatedTime: '10–14 min',
    rating: 4.8,
    playersCount: 38200,
    icon: Dna,
    colors: 'from-violet-600 via-purple-600 to-pink-500',
    badgeEmoji: '🧬',
    learning: ['Nucleotide base-pairing rules (A-T, G-C, A-U)', 'DNA replication mechanisms', 'Transcription from DNA to mRNA', 'Codon table and amino acid translation'],
    howToPlay: ['Pair incoming nucleotides with the exposed DNA template.', 'Transcribe mRNA and guide it through the ribosome.', 'Synthesize enzyme chains.'],
    stages: ['Double Helix Assembly', 'Transcription Fork', 'Ribosome Translation', 'Mutation Repair'],
    controlsDescription: 'Keyboard keys (A, T, C, G, U) or clickable nucleotide selector.',
  },
  {
    id: 'evolution-island',
    title: 'Evolution Island: Natural Selection',
    description: 'Guide creature populations through changing environments, adaptive mutations, predator pressures, and natural selection.',
    subject: 'Biology',
    difficulty: 'medium',
    classes: '8–12',
    classGrades: [8, 9, 10, 11, 12],
    genre: 'Simulation & Lab',
    xpReward: 160,
    estimatedTime: '12–16 min',
    rating: 4.8,
    playersCount: 33400,
    icon: TreePine,
    colors: 'from-green-600 via-emerald-500 to-teal-500',
    badgeEmoji: '🦎',
    learning: ['Darwinian natural selection & fitness', 'Genetic mutations and phenotypic variation', 'Camouflage and sexual selection', 'Speciation and extinction thresholds'],
    howToPlay: ['Introduce traits (beak shape, fur camouflage, running speed).', 'Subject the island to drought, ice ages, and invasive predators.', 'Ensure lineage survival.'],
    stages: ['Finch Archipelago', 'Predator Savannah', 'Glacial Ice Age', 'Adaptive Radiation'],
    controlsDescription: 'Trait selector cards and environmental sliders.',
  },
  {
    id: 'organ-medic',
    title: 'Organ Medic: Homeostasis Rescue',
    description: 'Manage human physiological systems in real time—maintain blood pressure, oxygen saturation, glucose, and body temperature.',
    subject: 'Biology',
    difficulty: 'medium',
    classes: '9–11',
    classGrades: [9, 10, 11],
    genre: 'Simulation & Lab',
    xpReward: 150,
    estimatedTime: '10–14 min',
    rating: 4.7,
    playersCount: 29700,
    icon: Activity,
    colors: 'from-rose-500 via-red-600 to-amber-600',
    badgeEmoji: '🫀',
    learning: ['Homeostasis feedback loops', 'Circulatory & respiratory gas exchange', 'Pancreatic insulin/glucagon regulation', 'Renal nephron fluid balance'],
    howToPlay: ['Monitor vitals (heart rate, SpO2, blood sugar, core temperature).', 'Administer physiological interventions to restore homeostasis.', 'Prevent organ failure.'],
    stages: ['Sprint Tachycardia', 'Hypoxia High Altitude', 'Diabetic Crisis', 'Intensive Care Homeostasis'],
    controlsDescription: 'Click physiological intervention dials and medication infusions.',
  },
  {
    id: 'microbe-hunter',
    title: 'Microbe Hunter: Microscope Explorer',
    description: 'Peer through high-powered optical microscopes to identify protozoa, bacteria, plant cells, and organelles.',
    subject: 'Biology',
    difficulty: 'easy',
    classes: '6–9',
    classGrades: [6, 7, 8, 9],
    genre: 'Adventure & Quest',
    xpReward: 130,
    estimatedTime: '8–12 min',
    rating: 4.6,
    playersCount: 25800,
    icon: Microscope,
    colors: 'from-cyan-500 via-blue-600 to-teal-600',
    badgeEmoji: '🦠',
    learning: ['Prokaryotic vs eukaryotic cell architecture', 'Amoeba pseudopodia, Paramecium cilia', 'Plant cell wall, vacuole & chloroplasts', 'Microscope magnification and focus knobs'],
    howToPlay: ['Focus the microscope lens using coarse and fine dials.', 'Identify moving microbes by their morphological features.', 'Classify specimens in your notebook.'],
    stages: ['Pond Water Drop', 'Onion Peel Slide', 'Cheek Cell Swab', 'Pathogen Classification'],
    controlsDescription: 'Focus knob drag wheels, slide pan controls, classification ledger.',
  },

  /* ======================================================================== */
  /*  6. ENGLISH & LANGUAGE ARTS (Classes 5–12)                               */
  /* ======================================================================== */
  {
    id: 'type-rush',
    title: 'Type Rush: Keyboard Grand Prix',
    description: 'Type fast, race faster! Real-time arcade racing propelled by touch-typing speed (WPM) and precision accuracy.',
    subject: 'English',
    difficulty: 'medium',
    classes: '5–12',
    classGrades: [5, 6, 7, 8, 9, 10, 11, 12],
    genre: 'Arcade & Racing',
    xpReward: 150,
    estimatedTime: '5–10 min',
    rating: 5.0,
    playersCount: 51200,
    icon: Keyboard,
    colors: 'from-rose-500 via-red-500 to-amber-500',
    badgeEmoji: '🏎️',
    learning: ['Touch-typing speed & muscle memory', 'Keystroke accuracy percentage', 'Real-time WPM acceleration', 'Educational literary passages'],
    howToPlay: ['Select your grade level passage.', 'Type the on-screen text accurately to propel your racing car.', 'Build streaks to trigger Turbo Nitro speed and overtake AI competitors!'],
    stages: ['Starting Grid', 'Nitro Straight', 'Championship Podium'],
    controlsDescription: 'Keyboard typing in real time.',
  },
  {
    id: 'word-runner',
    title: 'Word Runner: Lexicon Dash',
    description: 'Endless lane runner where recognizing prefixes, suffixes, root words, and spelling switches your runner safely.',
    subject: 'English',
    difficulty: 'easy',
    classes: '5–9',
    classGrades: [5, 6, 7, 8, 9],
    genre: 'Arcade & Racing',
    xpReward: 130,
    estimatedTime: '6–10 min',
    rating: 4.7,
    playersCount: 37400,
    icon: Zap,
    colors: 'from-indigo-600 via-purple-600 to-pink-500',
    badgeEmoji: '🏃',
    learning: ['Prefixes (un-, re-, pre-, dis-)', 'Suffixes (-tion, -ment, -ful, -able)', 'Correct spelling under time pressure', 'Compound word synthesis'],
    howToPlay: ['Dash forward through letter gates.', 'Swipe lanes to collect the correct affixes that complete the target word.', 'Dodge spelling traps.'],
    stages: ['Prefix Parkway', 'Suffix Speedway', 'Compound Causeway', 'Lexicon Loop'],
    controlsDescription: 'Left/Right Arrow keys or swipe to switch lanes.',
  },
  {
    id: 'grammar-kingdom',
    title: 'Grammar Kingdom: Castle Defense',
    description: 'Fortify your castle towers by correctly classifying parts of speech, active/passive voice, and subject-verb agreement.',
    subject: 'English',
    difficulty: 'medium',
    classes: '6–10',
    classGrades: [6, 7, 8, 9, 10],
    genre: 'Strategy & Building',
    xpReward: 150,
    estimatedTime: '10–14 min',
    rating: 4.8,
    playersCount: 32600,
    icon: Landmark,
    colors: 'from-purple-600 via-fuchsia-600 to-pink-600',
    badgeEmoji: '🏰',
    learning: ['Parts of speech (nouns, verbs, adjectives, adverbs, prepositions)', 'Subject-verb agreement rules', 'Active vs passive voice transformation', 'Clause identification (independent vs dependent)'],
    howToPlay: ['Enemy troops carry unparsed sentences.', 'Target incoming soldiers with arrow towers powered by the correct grammatical role.', 'Defend the realm.'],
    stages: ['Noun Bastion', 'Verb Rampart', 'Adverb Outpost', 'Citadel of Syntax'],
    controlsDescription: 'Click sentence tokens to assign grammatical ammunition to towers.',
  },
  {
    id: 'story-detective',
    title: 'Story Detective: The Clue in the Text',
    description: 'Solve noir mysteries by making inferences, spotting figurative language, deciphering tone, and identifying context clues.',
    subject: 'English',
    difficulty: 'hard',
    classes: '7–12',
    classGrades: [7, 8, 9, 10, 11, 12],
    genre: 'Adventure & Quest',
    xpReward: 170,
    estimatedTime: '12–16 min',
    rating: 4.9,
    playersCount: 28900,
    icon: Search,
    colors: 'from-slate-700 via-zinc-800 to-amber-600',
    badgeEmoji: '🕵️',
    learning: ['Textual inference and implicit meaning', 'Figurative devices (metaphor, simile, irony, hyperbole)', 'Author tone, mood, and perspective', 'Context clue vocabulary deduction'],
    howToPlay: ['Examine witness statements, diary entries, and evidence files.', 'Highlight figurative language and deduce hidden motives.', 'Unmask the culprit.'],
    stages: ['The Abandoned Manor', 'The Whispering Gallery', 'The Clockmaker’s Secret', 'Grand Courtroom Climax'],
    controlsDescription: 'Click to inspect case documents, drag evidence cards to deductive pinboard.',
  },
  {
    id: 'etymology-alchemist',
    title: 'Etymology Alchemist: Root Craft',
    description: 'Brew powerful vocabulary potions by combining ancient Greek and Latin roots, prefixes, and suffixes.',
    subject: 'English',
    difficulty: 'medium',
    classes: '7–11',
    classGrades: [7, 8, 9, 10, 11],
    genre: 'Puzzle & Logic',
    xpReward: 140,
    estimatedTime: '8–12 min',
    rating: 4.7,
    playersCount: 24100,
    icon: BookOpen,
    colors: 'from-amber-600 via-orange-600 to-emerald-600',
    badgeEmoji: '📖',
    learning: ['Greek roots (bio-, chrono-, tele-, auto-, photo-)', 'Latin roots (dict-, scrib-, port-, aud-, spect-)', 'Antonym & synonym relationships', 'High-frequency vocabulary expansion'],
    howToPlay: ['Combine root essence vials in the alchemical cauldron.', 'Transmute base roots into advanced academic vocabulary words.', 'Fill your Grimoire.'],
    stages: ['Novice Distiller', 'Greco-Roman Crucible', 'Polysyllabic Elixir', 'Master Lexicographer'],
    controlsDescription: 'Drag-and-drop root bottles into the brewing beaker.',
  },

  /* ======================================================================== */
  /*  7. HISTORY & SOCIAL STUDIES (Classes 6–12)                              */
  /* ======================================================================== */
  {
    id: 'history-quest',
    title: 'History Quest: Chronicles of India',
    description: 'Chronicles of Ancient India: Guide Chandragupta, accompany Xuanzang, and excavate Neolithic settlements.',
    subject: 'History',
    difficulty: 'medium',
    classes: '6–10',
    classGrades: [6, 7, 8, 9, 10],
    genre: 'Adventure & Quest',
    xpReward: 150,
    estimatedTime: '10–15 min',
    rating: 4.9,
    playersCount: 39400,
    icon: Landmark,
    colors: 'from-orange-600 via-amber-500 to-yellow-500',
    badgeEmoji: '🏺',
    learning: ['Mauryan Empire & Magadha trade routes', 'Xuanzang’s travels & King Harshavardhana', 'Neolithic archaeological sites (Burzahom, Mehrgarh)', 'Primary archaeological evidence'],
    howToPlay: ['Select your grade level to launch the interactive historical map.', 'Guide Xuanzang across ancient India to King Harsha’s court.', 'Excavate prehistoric artifacts.'],
    stages: ["The King's Road", "The Traveller's Path", "The Lost Settlements"],
    controlsDescription: 'Interactive map navigation, excavation grid clicking.',
    thumbnail: '/assets/thumbnails/history.jpg',
  },
  {
    id: 'indus-valley-builder',
    title: 'Civilization Builder: Indus Valley',
    description: 'Plan, build, and govern a Bronze Age Harappan metropolis with covered drainage, granaries, and grid streets.',
    subject: 'History',
    difficulty: 'medium',
    classes: '6–9',
    classGrades: [6, 7, 8, 9],
    genre: 'Strategy & Building',
    xpReward: 160,
    estimatedTime: '12–16 min',
    rating: 4.8,
    playersCount: 34200,
    icon: Landmark,
    colors: 'from-amber-700 via-yellow-600 to-stone-700',
    badgeEmoji: '🧱',
    learning: ['Harappan urban town planning (Citadel vs Lower Town)', 'Advanced covered brick drainage systems', 'Great Granaries & surplus agricultural economy', 'Trade seals and weight standards'],
    howToPlay: ['Lay out baked brick streets in perpendicular grid patterns.', 'Connect residential houses to main drain lines.', 'Manage grain stores and maritime trade through Lothal.'],
    stages: ['Settlement Foundation', 'Lower Town Grid', 'Great Bath & Citadel', 'Thriving Metropolis'],
    controlsDescription: 'City builder placement tools, resource management dashboard.',
  },
  {
    id: 'freedom-movement-quest',
    title: 'Freedom Movement: March to Independence',
    description: 'Experience India’s struggle for independence from 1857 to 1947 through pivotal decisions, satyagraha, and historic movements.',
    subject: 'History',
    difficulty: 'medium',
    classes: '8–10',
    classGrades: [8, 9, 10],
    genre: 'Adventure & Quest',
    xpReward: 160,
    estimatedTime: '12–16 min',
    rating: 4.9,
    playersCount: 36500,
    icon: Scroll,
    colors: 'from-orange-500 via-stone-100 to-emerald-600',
    badgeEmoji: '🕊️',
    learning: ['1857 Revolt and Queen’s Proclamation', 'Champaran Satyagraha & Non-Cooperation Movement', '1930 Dandi Salt March & Civil Disobedience', 'Quit India Movement 1942 & 1947 Independence'],
    howToPlay: ['Travel with freedom fighters along the Dandi March route.', 'Distribute pamphlets, mobilize peaceful protests, and avoid colonial crackdowns.', 'Raise the Tricolour.'],
    stages: ['First War of 1857', 'Champaran Awakening', 'Dandi Salt March', 'Dawn of Independence 1947'],
    controlsDescription: 'Dialogue decisions, route navigation, resource allocation.',
  },
  {
    id: 'emperors-court',
    title: 'Emperor’s Court: Statecraft & Trade',
    description: 'Balance diplomacy, religious tolerance, taxation, and architectural marvels in a historical court administration strategy game.',
    subject: 'History',
    difficulty: 'hard',
    classes: '7–10',
    classGrades: [7, 8, 9, 10],
    genre: 'Strategy & Building',
    xpReward: 170,
    estimatedTime: '12–18 min',
    rating: 4.7,
    playersCount: 27800,
    icon: Landmark,
    colors: 'from-rose-700 via-amber-600 to-purple-800',
    badgeEmoji: '👑',
    learning: ['Mansabdari military-administrative system', 'Zabt agricultural revenue assessment', 'Ibadat Khana & Sulh-i-kul policy', 'Monumental architecture (Fatehpur Sikri, Red Fort)'],
    howToPlay: ['Consult with the Navratnas (advisors).', 'Review petitions from farmers, merchants, and ambassadors.', 'Balance treasury funds, peace, and culture.'],
    stages: ['Ascension to the Throne', 'Revenue Reform', 'Court of Dialogues', 'Golden Age of Empire'],
    controlsDescription: 'Swipe/click decree cards Left or Right to make statecraft rulings.',
  },
  {
    id: 'artifact-archaeologist',
    title: 'Artifact Archaeologist: Strata Excavation',
    description: 'Unearth ancient pottery, coins, and inscriptions across geological strata and decipher Brahmi and Kharosthi scripts.',
    subject: 'History',
    difficulty: 'medium',
    classes: '6–11',
    classGrades: [6, 7, 8, 9, 10, 11],
    genre: 'Puzzle & Logic',
    xpReward: 140,
    estimatedTime: '10–14 min',
    rating: 4.7,
    playersCount: 23900,
    icon: Pickaxe,
    colors: 'from-amber-800 via-yellow-700 to-stone-600',
    badgeEmoji: '🪙',
    learning: ['Archaeological stratigraphy (Law of Superposition)', 'Carbon-14 dating principles', 'Ancient Indian scripts (Brahmi, Kharosthi)', 'Numismatic coin dating and trade evidence'],
    howToPlay: ['Delicately brush dirt from excavation trenches layer by layer.', 'Measure radiocarbon decay to date recovered relics.', 'Assemble broken pottery shards.'],
    stages: ['Upper Medieval Trench', 'Gupta Golden Layer', 'Mauryan Strata', 'Neolithic Bedrock'],
    controlsDescription: 'Trowel and brush mouse tools, relic assembly jigsaw grid.',
  },

  /* ======================================================================== */
  /*  8. GEOGRAPHY (Classes 6–12)                                             */
  /* ======================================================================== */
  {
    id: 'world-explorer',
    title: 'World Explorer: Coordinate Navigator',
    description: 'Pilot an exploration airship around the globe using latitude, longitude, the Prime Meridian, and international time zones.',
    subject: 'Geography',
    difficulty: 'medium',
    classes: '6–10',
    classGrades: [6, 7, 8, 9, 10],
    genre: 'Adventure & Quest',
    xpReward: 160,
    estimatedTime: '10–15 min',
    rating: 4.9,
    playersCount: 44100,
    icon: Globe,
    colors: 'from-blue-500 via-cyan-500 to-teal-500',
    badgeEmoji: '🌐',
    learning: ['Latitude, Longitude & Hemispheres', 'Equator, Tropics of Cancer & Capricorn', 'Greenwich Mean Time (GMT) & Indian Standard Time (IST)', 'Map projections and distance scales'],
    howToPlay: ['Set navigation coordinates (degrees North/South and East/West).', 'Calculate local flight arrival times based on timezone meridians.', 'Discover world capitals.'],
    stages: ['Equatorial Crossing', 'Greenwich Meridian Run', 'International Date Line', 'Global Circumnavigation'],
    controlsDescription: 'Interactive 3D globe click/drag, coordinate dial inputs.',
  },
  {
    id: 'climate-quest',
    title: 'Climate Quest: Biome Survival',
    description: 'Survive in distinct global climate zones—from equatorial rainforests to polar tundras—by understanding temperature and rainfall.',
    subject: 'Geography',
    difficulty: 'medium',
    classes: '7–11',
    classGrades: [7, 8, 9, 10, 11],
    genre: 'Simulation & Lab',
    xpReward: 150,
    estimatedTime: '10–14 min',
    rating: 4.8,
    playersCount: 31800,
    icon: Sun,
    colors: 'from-amber-500 via-emerald-600 to-cyan-600',
    badgeEmoji: '☀️',
    learning: ['Köppen climate classification', 'Lapse rate (temperature decrease with altitude)', 'Monsoon mechanism & rain shadow zones', 'Vegetation adaptations in extreme biomes'],
    howToPlay: ['Analyze climatographs displaying monthly rainfall and temperatures.', 'Equip your expedition with clothing and resources tailored to the biome.', 'Survive the season.'],
    stages: ['Congo Rainforest', 'Thar Desert', 'Alpine Himalaya', 'Arctic Tundra'],
    controlsDescription: 'Resource inventory management and climate data graph tools.',
  },
  {
    id: 'river-odyssey',
    title: 'River Odyssey: Source to Sea',
    description: 'Navigate a droplet of water from glacier source to oceanic delta, carving gorges, meanders, and fertile floodplains.',
    subject: 'Geography',
    difficulty: 'medium',
    classes: '7–10',
    classGrades: [7, 8, 9, 10],
    genre: 'Arcade & Racing',
    xpReward: 140,
    estimatedTime: '8–12 min',
    rating: 4.7,
    playersCount: 29500,
    icon: Waves,
    colors: 'from-cyan-600 via-blue-600 to-indigo-700',
    badgeEmoji: '🌊',
    learning: ['Upper river course: V-shaped valleys, waterfalls, gorges', 'Middle course: meanders, oxbow lakes, erosion vs deposition', 'Lower course: floodplains, estuaries, deltas', 'Sediment load transport'],
    howToPlay: ['Steer water flow down mountain gradients.', 'Erode riverbanks on outer bends and deposit silt on inner point bars.', 'Form the grand delta.'],
    stages: ['Glacial Torrent', 'Ganyon Rapids', 'Meandering Plains', 'Sundarbans Delta'],
    controlsDescription: 'Arrow keys / A & D to steer current flow and deposit silt.',
  },
  {
    id: 'geo-disaster-command',
    title: 'Geo Disaster Command',
    description: 'Real-time emergency management simulation: predict cyclones, mitigate earthquakes along fault lines, and deploy tsunami warnings.',
    subject: 'Geography',
    difficulty: 'hard',
    classes: '8–11',
    classGrades: [8, 9, 10, 11],
    genre: 'Strategy & Building',
    xpReward: 180,
    estimatedTime: '12–16 min',
    rating: 4.9,
    playersCount: 37200,
    icon: Shield,
    colors: 'from-red-600 via-orange-600 to-stone-800',
    badgeEmoji: '🚨',
    learning: ['Ring of Fire & seismic hazard zones', 'Tropical cyclone formation (Coriolis effect & warm SST)', 'Tsunami deep-water wave propagation', 'Disaster vulnerability and mitigation protocols'],
    howToPlay: ['Track satellite radar for cyclone atmospheric pressure drops.', 'Issue coastal evacuation orders and reinforce sea dykes.', 'Save coastal populations.'],
    stages: ['Bay of Bengal Cyclone', 'Himalayan Seismic Hazard', 'Indian Ocean Tsunami Watch', 'National Disaster HQ'],
    controlsDescription: 'Interactive radar map, evacuation deployment buttons.',
  },
  {
    id: 'resources-of-india',
    title: 'Resources of India: Economic Tycoon',
    description: 'Build sustainable supply chains connecting iron ore, coal, cotton soils, solar corridors, and industrial corridors.',
    subject: 'Geography',
    difficulty: 'medium',
    classes: '9–12',
    classGrades: [9, 10, 11, 12],
    genre: 'Strategy & Building',
    xpReward: 160,
    estimatedTime: '12–18 min',
    rating: 4.8,
    playersCount: 26100,
    icon: MapPin,
    colors: 'from-emerald-700 via-teal-700 to-amber-600',
    badgeEmoji: '🗺️',
    learning: ['Mineral belts (Chota Nagpur coal & iron ore)', 'Soil distribution (Black Regur, Alluvial, Red & Laterite)', 'Agro-climatic crop zones (Wheat, Rice, Cotton, Tea)', 'Green energy corridors & freight hubs'],
    howToPlay: ['Establish resource extraction sites on geologically verified belts.', 'Construct railway freight corridors connecting raw materials to manufacturing centers.', 'Maintain green sustainability scores.'],
    stages: ['Chota Nagpur Minerals', 'Deccan Cotton Corridor', 'Green Revolution Plains', 'National Green Grid'],
    controlsDescription: 'Map placement grid, economic budget ledger, supply line connector.',
  },

  /* ======================================================================== */
  /*  9. COMPUTER SCIENCE & INFORMATICS (Classes 6–12)                        */
  /* ======================================================================== */
  {
    id: 'algorithm-arena',
    title: 'Algorithm Arena: The Sorting Race',
    description: 'Race against time and sorting algorithms! Compare Bubble, Insertion, Quick, and Merge sort through interactive array battles.',
    subject: 'Computer Science',
    difficulty: 'medium',
    classes: '8–12',
    classGrades: [8, 9, 10, 11, 12],
    genre: 'Puzzle & Logic',
    xpReward: 170,
    estimatedTime: '10–15 min',
    rating: 4.9,
    playersCount: 45800,
    icon: Workflow,
    colors: 'from-blue-600 via-indigo-600 to-cyan-500',
    badgeEmoji: '📊',
    learning: ['Comparison-based sorting (Bubble, Insertion, Selection)', 'Divide-and-conquer algorithms (Merge Sort, Quick Sort)', 'Time complexity analysis (O(n^2) vs O(n log n))', 'Space complexity & array pointers'],
    howToPlay: ['Manually execute comparisons and swaps on array elements.', 'Beat the automated AI algorithm bots with fewer operations.', 'Master algorithm efficiency.'],
    stages: ['Bubble Sprint', 'Insertion Climb', 'Merge Sort Division', 'Quick Sort Partition'],
    controlsDescription: 'Click adjacent array bars to compare/swap, or click pivot points.',
  },
  {
    id: 'binary-blitz',
    title: 'Binary Blitz: Bitwise Battle',
    description: 'Fast-paced arcade action converting decimal numbers to binary, toggling 8-bit bytes, and firing logic gates (AND, OR, XOR, NOT).',
    subject: 'Computer Science',
    difficulty: 'medium',
    classes: '6–11',
    classGrades: [6, 7, 8, 9, 10, 11],
    genre: 'Arcade & Racing',
    xpReward: 160,
    estimatedTime: '6–10 min',
    rating: 4.8,
    playersCount: 39900,
    icon: Binary,
    colors: 'from-emerald-500 via-teal-600 to-slate-900',
    badgeEmoji: '👾',
    learning: ['Binary number system (powers of 2: 128, 64, 32, 16, 8, 4, 2, 1)', 'Hexadecimal notation basics', 'Bitwise operations (AND, OR, XOR, NOT, NAND)', 'Bit shifting (<<, >>) and overflow'],
    howToPlay: ['Enemy numbers drop down matrix columns.', 'Toggle 8-bit switches (0/1) to match the target decimal value.', 'Blast waves with logic gate laser cannons.'],
    stages: ['Byte Basics', 'Bitwise Brawlers', 'Hexadecimal Highway', 'Matrix Overdrive'],
    controlsDescription: 'Click 8-bit switch toggles (1-8 on keyboard), select logic gates.',
  },
  {
    id: 'code-maze',
    title: 'Code Maze: Turtle Bot',
    description: 'Program a lovable autonomous robot through hazard-filled labyrinths using visual blocks, loops, conditions, and procedures.',
    subject: 'Computer Science',
    difficulty: 'easy',
    classes: '5–9',
    classGrades: [5, 6, 7, 8, 9],
    genre: 'Puzzle & Logic',
    xpReward: 140,
    estimatedTime: '10–14 min',
    rating: 4.8,
    playersCount: 36200,
    icon: Bot,
    colors: 'from-cyan-500 via-blue-600 to-indigo-600',
    badgeEmoji: '🤖',
    learning: ['Program sequencing & state execution', 'Loops (repeat N times, while not at goal)', 'Conditional branching (if obstacle then turn)', 'Functions & procedural reusability'],
    howToPlay: ['Assemble visual programming blocks into the command stack.', 'Hit Run to execute instructions and watch Turtle Bot navigate.', 'Collect all stars.'],
    stages: ['Straight Sequence', 'Loop Lagoon', 'Conditional Canyon', 'Function Fortress'],
    controlsDescription: 'Drag-and-drop block coding queue, click Step/Run.',
  },
  {
    id: 'network-packet-route',
    title: 'Network Packet Route: Internet Highway',
    description: 'Route data packets across switches, routers, and undersea cables while dodging congestion, latency, and firewall threats.',
    subject: 'Computer Science',
    difficulty: 'hard',
    classes: '9–12',
    classGrades: [9, 10, 11, 12],
    genre: 'Simulation & Lab',
    xpReward: 180,
    estimatedTime: '12–16 min',
    rating: 4.9,
    playersCount: 31400,
    icon: Radio,
    colors: 'from-violet-600 via-indigo-600 to-cyan-500',
    badgeEmoji: '🌐',
    learning: ['OSI & TCP/IP 4-layer model', 'IP addressing & subnet masks', 'DNS name resolution & packet headers', 'Packet loss, latency, and DDoS firewall filtering'],
    howToPlay: ['Configure routing tables at network hubs.', 'Direct TCP data streams around broken trunk cables to maintain ping < 30ms.', 'Inspect packet headers.'],
    stages: ['Local Area Network (LAN)', 'Autonomous System Routing', 'Transatlantic Undersea Fiber', 'Global Cloud Backbone'],
    controlsDescription: 'Click router ports to establish routing paths and inspect packet headers.',
  },
  {
    id: 'cyber-sentinel',
    title: 'Cyber Sentinel: Cryptography Escape',
    description: 'Crack historical ciphers, analyze letter frequency distributions, and configure RSA public-key encryption to escape.',
    subject: 'Computer Science',
    difficulty: 'hard',
    classes: '8–12',
    classGrades: [8, 9, 10, 11, 12],
    genre: 'Puzzle & Logic',
    xpReward: 190,
    estimatedTime: '12–18 min',
    rating: 4.9,
    playersCount: 33100,
    icon: KeyRound,
    colors: 'from-slate-800 via-emerald-600 to-cyan-500',
    badgeEmoji: '🔐',
    learning: ['Caesar shift & substitution ciphers', 'Frequency analysis of ciphertexts', 'Cryptographic hashing (SHA-256 integrity)', 'Symmetric vs asymmetric RSA public/private keys'],
    howToPlay: ['Rotate cipher wheels to decode intercept transmissions.', 'Use histogram frequency counters to break substitution alphabets.', 'Safely exchange keys.'],
    stages: ['Caesar’s Rotator', 'Vigenère Polyalphabetic Table', 'Hash Integrity Checksum', 'RSA Key Exchange Vault'],
    controlsDescription: 'Rotate cipher rings, type decoded deciphered text, inspect hash strings.',
  },

  // ==========================================
  // 10. MIND & MEMORY (5 Games)
  // ==========================================
  {
    id: 'memory-vault',
    title: 'Memory Vault',
    description: 'Enter mysterious ancient chambers where artifacts flash briefly before disappearing. Remember positions, sequences, and relationships to safely retrieve the relic.',
    subject: 'Mind & Memory',
    difficulty: 'medium',
    classes: '5–12',
    classGrades: [5, 6, 7, 8, 9, 10, 11, 12],
    genre: 'Adventure & Quest',
    xpReward: 160,
    estimatedTime: '8–12 min',
    rating: 4.9,
    playersCount: 28400,
    icon: Brain,
    colors: 'from-purple-900 via-indigo-700 to-amber-500',
    badgeEmoji: '🏛️',
    tagline: 'Remember the room. Escape before time runs out.',
    learning: ['Spatial working memory retention', 'Multi-item positional recall', 'Chunking and relational indexing', 'Focus under time constraints'],
    howToPlay: ['Observe the chamber for 5 seconds as relics glow.', 'Once artifacts vanish, click the correct pedestal slots to restore them.', 'Maintain combos and beat the timer to unlock deeper vault chambers!'],
    stages: ['Chamber of Bronze', 'Chamber of Silver', 'Hall of Obsidian', 'The Master Sanctuary'],
    controlsDescription: 'Mouse click / tap pedestals in remembered order, or use number keys 1–9.',
  },
  {
    id: 'pattern-pulse',
    title: 'Pattern Pulse',
    description: 'Feel the rhythm and test your working memory! Dynamic sequences of colored geometric pulses and musical resonance challenge your pattern recognition.',
    subject: 'Mind & Memory',
    difficulty: 'easy',
    classes: '5–12',
    classGrades: [5, 6, 7, 8, 9, 10, 11, 12],
    genre: 'Puzzle & Logic',
    xpReward: 150,
    estimatedTime: '6–10 min',
    rating: 4.8,
    playersCount: 36200,
    icon: Activity,
    colors: 'from-cyan-600 via-fuchsia-600 to-violet-800',
    badgeEmoji: '💫',
    tagline: 'Feel the rhythm. Master the sequence.',
    learning: ['Auditory and visual pattern recognition', 'Sequential working memory expansion', 'Rhythmic timing and cognitive tempo', 'Error suppression'],
    howToPlay: ['Watch and listen as colored pads illuminate in sequence.', 'Reproduce the exact pattern by tapping the illuminated nodes.', 'Beat higher stages as sequence length and speed increase!'],
    stages: ['Harmonic Warmup (4 steps)', 'Resonant Flow (6 steps)', 'Synaptic Surge (8 steps)', 'Master Maestro (10+ steps)'],
    controlsDescription: 'Click colored pads or press keys 1, 2, 3, 4 (or Q, W, E, R).',
  },
  {
    id: 'memory-maze',
    title: 'Memory Maze',
    description: 'A treacherous labyrinth path illuminates briefly, then shrouds itself in darkness. Guide your adventurer through the hidden route relying solely on memory!',
    subject: 'Mind & Memory',
    difficulty: 'medium',
    classes: '5–12',
    classGrades: [5, 6, 7, 8, 9, 10, 11, 12],
    genre: 'Adventure & Quest',
    xpReward: 175,
    estimatedTime: '8–14 min',
    rating: 4.9,
    playersCount: 31500,
    icon: Compass,
    colors: 'from-emerald-800 via-teal-700 to-indigo-900',
    badgeEmoji: '🧭',
    tagline: 'Memorize the labyrinth. Step with confidence.',
    learning: ['Spatial navigation & cognitive mapping', 'Short-term visual trace retention', 'Inhibition of impulsive missteps', 'Working memory under fog-of-war'],
    howToPlay: ['Memorize the golden path before the fog descends.', 'Use arrow keys or directional buttons to navigate tile by tile.', 'Avoid hidden trap tiles that cost lives and safely reach the portal!'],
    stages: ['Forest Glade (4x4)', 'Dungeon Corridor (5x5)', 'Catacombs (6x6)', 'The Labyrinth of Shadows (7x7)'],
    controlsDescription: 'Use Arrow Keys, WASD, or on-screen directional buttons to step.',
  },
  {
    id: 'sequence-builder',
    title: 'Sequence Builder',
    description: 'Deduce logical progressions across numbers, geometric rotations, color spectrums, and historical timelines. Drag and place elements to forge flawless chains.',
    subject: 'Mind & Memory',
    difficulty: 'hard',
    classes: '5–12',
    classGrades: [5, 6, 7, 8, 9, 10, 11, 12],
    genre: 'Puzzle & Logic',
    xpReward: 180,
    estimatedTime: '10–15 min',
    rating: 4.8,
    playersCount: 22700,
    icon: Workflow,
    colors: 'from-blue-700 via-indigo-600 to-pink-600',
    badgeEmoji: '🧩',
    tagline: 'Connect the logic. Build the master sequence.',
    learning: ['Inductive & deductive sequence reasoning', 'Fibonacci, arithmetic & geometric progressions', 'Rotational symmetry analysis', 'Logical ordering of causal events'],
    howToPlay: ['Inspect the sequence pattern with a missing slot.', 'Analyze the underlying mathematical or logical rule.', 'Select and place the missing piece to complete the chain!'],
    stages: ['Linear Arithmetic', 'Geometric Rotation', 'Fibonacci Spirals', 'Dual Interleaved Patterns'],
    controlsDescription: 'Click and drag sequence tiles into the target placeholder slot.',
  },
  {
    id: 'focus-hunter',
    title: 'Focus Hunter',
    description: 'High-speed cognitive attention arena! Rapidly spot and capture target items while resisting visual distractors, dynamic decoys, and shifting color camouflage.',
    subject: 'Mind & Memory',
    difficulty: 'medium',
    classes: '5–12',
    classGrades: [5, 6, 7, 8, 9, 10, 11, 12],
    genre: 'Arcade & Racing',
    xpReward: 165,
    estimatedTime: '5–10 min',
    rating: 4.9,
    playersCount: 41200,
    icon: Target,
    colors: 'from-amber-600 via-rose-600 to-purple-800',
    badgeEmoji: '🎯',
    tagline: 'Zero in on target. Eliminate distractions.',
    learning: ['Selective visual attention & search speed', 'Distractor suppression (Stroop effect)', 'Rapid reaction time & motor impulse control', 'High-speed cognitive filtering'],
    howToPlay: ['Check the primary target symbol displayed at the top.', 'Tap the target instances quickly as they move across the observation field.', 'Avoid decoy distractors to build streak multipliers!'],
    stages: ['Static Field Focus', 'Moving Swarm', 'Color Camouflage', 'Hyper Velocity Drift'],
    controlsDescription: 'Click / tap target items with mouse or touchscreen.',
  },

  // ==========================================
  // 11. DETECTIVE & LOGIC (5 Games)
  // ==========================================
  {
    id: 'missing-artifact',
    title: 'The Missing Artifact',
    description: 'A priceless ancient Harappan relic has vanished from the museum vault. Investigate crime scene rooms, analyze forensic clues, expose suspect contradictions, and crack the case!',
    subject: 'Detective & Logic',
    difficulty: 'medium',
    classes: '5–12',
    classGrades: [5, 6, 7, 8, 9, 10, 11, 12],
    genre: 'Adventure & Quest',
    xpReward: 200,
    estimatedTime: '12–18 min',
    rating: 5.0,
    playersCount: 38900,
    icon: Search,
    colors: 'from-amber-800 via-orange-900 to-stone-900',
    badgeEmoji: '🏺',
    tagline: 'Inspect the crime scene. Recover the stolen relic.',
    learning: ['Forensic observation & evidence gathering', 'Cross-referencing witness statements', 'Detecting logical contradictions & false alibis', 'Hypothesis deduction from physical traces'],
    howToPlay: ['Explore the 4 crime scene zones: Pedestal, Security Room, Service Vent, and Curator Desk.', 'Collect physical evidence and inspect suspect statements.', 'Pinpoint the culprit whose alibi contradicts forensic proof!'],
    stages: ['Crime Scene Walkthrough', 'Forensic Lab Analysis', 'Suspect Interrogation', 'The Accusation'],
    controlsDescription: 'Click crime scene hotspots to examine, collect clues, and open investigation dossier.',
  },
  {
    id: 'codebreaker',
    title: 'Codebreaker: The Master Vault',
    description: 'Mechanical safe cracking and deductive cryptanalysis! Use logic pins, parity checks, and position feedback clues to deduce secret security passcodes.',
    subject: 'Detective & Logic',
    difficulty: 'hard',
    classes: '5–12',
    classGrades: [5, 6, 7, 8, 9, 10, 11, 12],
    genre: 'Puzzle & Logic',
    xpReward: 190,
    estimatedTime: '10–15 min',
    rating: 4.9,
    playersCount: 29800,
    icon: KeyRound,
    colors: 'from-slate-900 via-blue-900 to-cyan-600',
    badgeEmoji: '🔐',
    tagline: 'Decipher the tumblers. Crack the master vault.',
    learning: ['Deductive logic & hypothesis testing', 'Combinatorial permutations & constraints', 'Systematic elimination strategies', 'Binary parity & numerical clues'],
    howToPlay: ['Dial your proposed code combination into the vault tumblers.', 'Inspect green pins (correct digit & position) and amber pins (correct digit, wrong place).', 'Crack the code before security lockouts engage!'],
    stages: ['Bronze Safe (3 Digits)', 'Silver Vault (4 Digits)', 'Titanium Stronghold (4 Digits + Symbols)', 'Quantum Vault (5 Digits + Parity)'],
    controlsDescription: 'Click tumbler arrows to cycle numbers or type with keyboard numpad.',
  },
  {
    id: 'detectives-office',
    title: "Detective's Office: Case Corkboard",
    description: 'Assemble the master evidence board! Connect suspects, motive notes, forensic fibers, and time-stamped alibis with red yarn to solve high-stakes mysteries.',
    subject: 'Detective & Logic',
    difficulty: 'medium',
    classes: '5–12',
    classGrades: [5, 6, 7, 8, 9, 10, 11, 12],
    genre: 'Adventure & Quest',
    xpReward: 210,
    estimatedTime: '12–16 min',
    rating: 4.9,
    playersCount: 34100,
    icon: Landmark,
    colors: 'from-stone-900 via-amber-950 to-red-900',
    badgeEmoji: '📌',
    tagline: 'Connect the evidence. Unravel the conspiracy.',
    learning: ['Relational diagramming & graph networks', 'Motive, means, and opportunity assessment', 'Causal inference & timeline construction', 'Critical thinking without jumping to conclusions'],
    howToPlay: ['Review evidence cards pinned to the corkboard.', 'Drag red yarn threads between related cards (Suspect + Weapon + Location).', 'Validate connections to uncover the smoking gun!'],
    stages: ['The Midnight Heist', 'The Forged Manuscript', 'The Blackout Sabotage', 'The Grand Conspiracy'],
    controlsDescription: 'Drag from pin to pin to connect red yarn; click cards to inspect detailed evidence notes.',
  },
  {
    id: 'time-travel-mystery',
    title: 'The Time Travel Mystery',
    description: 'Historical anomalies threaten the spacetime continuum! Travel through ancient civilizations, discover out-of-place artifacts, and resolve chronological paradoxes.',
    subject: 'Detective & Logic',
    difficulty: 'medium',
    classes: '5–12',
    classGrades: [5, 6, 7, 8, 9, 10, 11, 12],
    genre: 'Adventure & Quest',
    xpReward: 220,
    estimatedTime: '14–20 min',
    rating: 5.0,
    playersCount: 36700,
    icon: Rocket,
    colors: 'from-indigo-900 via-purple-800 to-amber-600',
    badgeEmoji: '⏳',
    tagline: 'Fix the timeline. Repair history’s paradoxes.',
    learning: ['Historical chronology & technological milestones', 'Identifying historical anachronisms', 'Causal sequencing of civilization eras', 'Comparative civilizational analysis'],
    howToPlay: ['Leap through portals across Indus Valley, Roman Empire, Renaissance Florence, and Industrial London.', 'Detect objects that do not belong to that era.', 'Restore timeline integrity and capture the rogue chrononaut!'],
    stages: ['Indus Valley 2500 BCE', 'Roman Senate 44 BCE', 'Leonardo’s Workshop 1500 CE', 'Apollo Launchpad 1969 CE'],
    controlsDescription: 'Click time eras to travel; click anachronistic items to scan with chronological scanner.',
  },
  {
    id: 'logic-detective',
    title: 'Logic Detective: The Grid Matrix',
    description: 'The ultimate pure deduction puzzle! Use deductive clues to eliminate possibilities on an interactive matrix grid: deduce Who, Where, When, and What Happened.',
    subject: 'Detective & Logic',
    difficulty: 'hard',
    classes: '5–12',
    classGrades: [5, 6, 7, 8, 9, 10, 11, 12],
    genre: 'Puzzle & Logic',
    xpReward: 200,
    estimatedTime: '10–18 min',
    rating: 4.9,
    playersCount: 27900,
    icon: Boxes,
    colors: 'from-slate-900 via-emerald-800 to-teal-600',
    badgeEmoji: '🔎',
    tagline: 'Eliminate the impossible. Deduce the truth.',
    learning: ['Matrix grid deduction (Einstein / Zebra puzzle mechanics)', 'Direct & indirect logical proposition parsing', 'Binary constraint satisfaction', 'Rigorous systematic proof derivation'],
    howToPlay: ['Read clues such as "Dr. Evans was not in the Conservatory".', 'Click grid cells once for Cross (✗ - impossible), twice for Checkmark (✓ - confirmed).', 'Let logic deductions chain reaction to solve the entire mystery matrix!'],
    stages: ['The 3x3 Warmup', 'The 4x4 Mansion Case', 'The 4-Category Master Case', 'The Grand Inspector Exam'],
    controlsDescription: 'Click grid cells to cycle between blank, ✗ (eliminate), and ✓ (confirm).',
  },
];

export const getGameById = (id: string): GameDefinition | undefined =>
  GAME_CATALOG.find((game) => game.id === id);

export const getGamesBySubject = (subject: AcademicSubjectName): GameDefinition[] =>
  GAME_CATALOG.filter((game) => game.subject === subject);

export const getGamesByClass = (grade: number): GameDefinition[] =>
  GAME_CATALOG.filter((game) => game.classGrades.includes(grade));
