import type { TrigQuestion, StageConfig } from './types';

export const STAGE_CONFIGS: StageConfig[] = [
  {
    id: 1,
    name: 'Stage 1',
    title: 'Angle Hunter',
    description: 'Hunt down the basic values of standard angles in right triangles.',
    icon: '🎯',
    requiredQuestions: 4,
  },
  {
    id: 2,
    name: 'Stage 2',
    title: 'Special Angles',
    description: 'Master exact fraction & radical values for 0°, 30°, 45°, 60°, and 90°.',
    icon: '📐',
    requiredQuestions: 4,
  },
  {
    id: 3,
    name: 'Stage 3',
    title: 'Unit Circle Explorer',
    description: 'Connect angles on the circle to coordinates (cos θ, sin θ).',
    icon: '⭕',
    requiredQuestions: 4,
  },
  {
    id: 4,
    name: 'Stage 4',
    title: 'Quadrant Battle',
    description: 'Conquer the 4 quadrants using the ASTC sign rule.',
    icon: '⚔️',
    requiredQuestions: 4,
  },
  {
    id: 5,
    name: 'Stage 5',
    title: 'Find The Angle',
    description: 'Reverse the equations to find single and multi-quadrant angle solutions.',
    icon: '🔍',
    requiredQuestions: 4,
  },
  {
    id: 6,
    name: 'Stage 6',
    title: 'Speed Round',
    description: '30 seconds rapid-fire streak challenge! Rack up combos for bonus XP.',
    icon: '⚡',
    requiredQuestions: 8,
  },
  {
    id: 7,
    name: 'Stage 7',
    title: 'Final Trigonometry Boss',
    description: 'Defeat the Trigonometry Titan by solving mixed master-level problems!',
    icon: '👑',
    requiredQuestions: 6,
  },
];

export const TRIG_QUESTIONS: TrigQuestion[] = [
  /* ---------------- STAGE 1: ANGLE HUNTER ---------------- */
  {
    id: 's1_q1',
    stage: 1,
    topic: 'sin',
    subTopic: '30 degrees',
    angleDeg: 30,
    question: 'What is the exact value of sin(30°)?',
    equation: '\\sin(30^\\circ) = ?',
    options: ['1/2', '√2/2', '√3/2', '1'],
    correctAnswer: '1/2',
    explanation: 'In a 30°-60°-90° special right triangle, opposite/hypotenuse for 30° is 1/2.',
    hint: '30° is the smallest standard angle; sin starts small at 1/2.',
  },
  {
    id: 's1_q2',
    stage: 1,
    topic: 'cos',
    subTopic: '60 degrees',
    angleDeg: 60,
    question: 'What is the exact value of cos(60°)?',
    equation: '\\cos(60^\\circ) = ?',
    options: ['1/2', '√3/2', '√2/2', '0'],
    correctAnswer: '1/2',
    explanation: 'By co-function identities, cos(60°) = sin(30°) = 1/2.',
    hint: 'Complementary angles have equal sine and cosine values: cos(60°) = sin(90° - 60°).',
  },
  {
    id: 's1_q3',
    stage: 1,
    topic: 'tan',
    subTopic: '45 degrees',
    angleDeg: 45,
    question: 'What is the exact value of tan(45°)?',
    equation: '\\tan(45^\\circ) = ?',
    options: ['1', '0', '√3', '1/√3'],
    correctAnswer: '1',
    explanation: 'In a 45°-45°-90° triangle, opposite = adjacent, so tan(45°) = 1.',
    hint: 'At 45°, opposite side equals adjacent side.',
  },
  {
    id: 's1_q4',
    stage: 1,
    topic: 'sin',
    subTopic: '90 degrees',
    angleDeg: 90,
    question: 'What is the value of sin(90°)?',
    equation: '\\sin(90^\\circ) = ?',
    options: ['1', '0', '1/2', '-1'],
    correctAnswer: '1',
    explanation: 'On the unit circle, the y-coordinate at 90° (0, 1) is 1. Therefore sin(90°) = 1.',
  },
  {
    id: 's1_q5',
    stage: 1,
    topic: 'cos',
    subTopic: '0 degrees',
    angleDeg: 0,
    question: 'What is the value of cos(0°)?',
    equation: '\\cos(0^\\circ) = ?',
    options: ['1', '0', '1/2', '√3/2'],
    correctAnswer: '1',
    explanation: 'At 0°, the point on the unit circle is (1, 0). The x-coordinate represents cosine, so cos(0°) = 1.',
  },

  /* ---------------- STAGE 2: SPECIAL ANGLES ---------------- */
  {
    id: 's2_q1',
    stage: 2,
    topic: 'specialAngles',
    subTopic: 'sin 45',
    angleDeg: 45,
    question: 'What is the exact value of sin(45°)?',
    equation: '\\sin(45^\\circ) = ?',
    options: ['√2/2', '1/2', '√3/2', '1'],
    correctAnswer: '√2/2',
    explanation: 'In an isosceles right triangle (45°-45°-90°), sin(45°) = 1/√2 = √2/2.',
  },
  {
    id: 's2_q2',
    stage: 2,
    topic: 'specialAngles',
    subTopic: 'cos 30',
    angleDeg: 30,
    question: 'What is the exact value of cos(30°)?',
    equation: '\\cos(30^\\circ) = ?',
    options: ['√3/2', '1/2', '√2/2', '1'],
    correctAnswer: '√3/2',
    explanation: 'In a 30°-60°-90° triangle, the adjacent side to 30° is √3, giving cos(30°) = √3/2.',
  },
  {
    id: 's2_q3',
    stage: 2,
    topic: 'specialAngles',
    subTopic: 'tan 30',
    angleDeg: 30,
    question: 'What is the exact value of tan(30°)?',
    equation: '\\tan(30^\\circ) = ?',
    options: ['√3/3', '√3', '1', '1/2'],
    correctAnswer: '√3/3',
    explanation: 'tan(30°) = sin(30°)/cos(30°) = (1/2) / (√3/2) = 1/√3 = √3/3.',
  },
  {
    id: 's2_q4',
    stage: 2,
    topic: 'specialAngles',
    subTopic: 'tan 60',
    angleDeg: 60,
    question: 'What is the exact value of tan(60°)?',
    equation: '\\tan(60^\\circ) = ?',
    options: ['√3', '√3/3', '1', '2'],
    correctAnswer: '√3',
    explanation: 'tan(60°) = sin(60°)/cos(60°) = (√3/2) / (1/2) = √3.',
  },
  {
    id: 's2_q5',
    stage: 2,
    topic: 'specialAngles',
    subTopic: 'tan 90',
    angleDeg: 90,
    question: 'What is the value of tan(90°)?',
    equation: '\\tan(90^\\circ) = ?',
    options: ['Undefined', '0', '1', '∞'],
    correctAnswer: 'Undefined',
    explanation: 'tan(90°) = sin(90°)/cos(90°) = 1/0, which is undefined due to vertical asymptote.',
  },

  /* ---------------- STAGE 3: UNIT CIRCLE ---------------- */
  {
    id: 's3_q1',
    stage: 3,
    topic: 'unitCircle',
    subTopic: 'coordinate representation',
    question: 'On the unit circle with radius 1, any angle θ corresponds to the Cartesian point:',
    equation: '(x, y) = ?',
    options: ['(cos θ, sin θ)', '(sin θ, cos θ)', '(tan θ, 1)', '(1, tan θ)'],
    correctAnswer: '(cos θ, sin θ)',
    explanation: 'By unit circle definition: x = cos(θ) and y = sin(θ).',
  },
  {
    id: 's3_q2',
    stage: 3,
    topic: 'unitCircle',
    subTopic: '180 degrees point',
    angleDeg: 180,
    question: 'What is the coordinate point on the unit circle at θ = 180° (π radians)?',
    options: ['(-1, 0)', '(0, -1)', '(1, 0)', '(0, 1)'],
    correctAnswer: '(-1, 0)',
    explanation: 'At 180°, x = cos(180°) = -1 and y = sin(180°) = 0, giving point (-1, 0).',
  },
  {
    id: 's3_q3',
    stage: 3,
    topic: 'unitCircle',
    subTopic: '270 degrees',
    angleDeg: 270,
    question: 'What are the values of cos(270°) and sin(270°)?',
    options: [
      'cos = 0, sin = -1',
      'cos = -1, sin = 0',
      'cos = 0, sin = 1',
      'cos = 1, sin = -1',
    ],
    correctAnswer: 'cos = 0, sin = -1',
    explanation: 'At 270° (bottom of unit circle), coordinates are (0, -1), so cos(270°)=0 and sin(270°)=-1.',
  },
  {
    id: 's3_q4',
    stage: 3,
    topic: 'unitCircle',
    subTopic: 'radian conversion',
    question: 'What is 60° expressed in radians?',
    options: ['π/3', 'π/6', 'π/4', '2π/3'],
    correctAnswer: 'π/3',
    explanation: 'Radians = Degrees × (π / 180°) = 60° × (π / 180°) = π/3.',
  },
  {
    id: 's3_q5',
    stage: 3,
    topic: 'unitCircle',
    subTopic: '120 degrees coordinates',
    angleDeg: 120,
    question: 'At angle θ = 120° in Quadrant II, what is the point (x, y)?',
    options: ['(-1/2, √3/2)', '(1/2, √3/2)', '(-√3/2, 1/2)', '(-√2/2, √2/2)'],
    correctAnswer: '(-1/2, √3/2)',
    explanation: 'cos(120°) = -cos(60°) = -1/2, and sin(120°) = sin(60°) = √3/2.',
  },

  /* ---------------- STAGE 4: QUADRANT BATTLE ---------------- */
  {
    id: 's4_q1',
    stage: 4,
    topic: 'quadrants',
    subTopic: 'ASTC rule',
    question: 'In which quadrant are BOTH sin(θ) and cos(θ) POSITIVE?',
    options: ['Quadrant I', 'Quadrant II', 'Quadrant III', 'Quadrant IV'],
    correctAnswer: 'Quadrant I',
    explanation: 'In Quadrant I (0° to 90°), all trigonometric functions are positive (A in ASTC).',
  },
  {
    id: 's4_q2',
    stage: 4,
    topic: 'quadrants',
    subTopic: 'Quadrant II signs',
    question: 'In which quadrant is sin(θ) POSITIVE while cos(θ) is NEGATIVE?',
    options: ['Quadrant II', 'Quadrant I', 'Quadrant III', 'Quadrant IV'],
    correctAnswer: 'Quadrant II',
    explanation: 'In Quadrant II (90° to 180°), only Sine is positive (S in ASTC); Cosine and Tangent are negative.',
  },
  {
    id: 's4_q3',
    stage: 4,
    topic: 'quadrants',
    subTopic: 'Quadrant III tan sign',
    question: 'What is the sign of tan(θ) in Quadrant III (180° < θ < 270°)?',
    options: ['Positive (+)', 'Negative (-)', 'Zero', 'Undefined'],
    correctAnswer: 'Positive (+)',
    explanation: 'In Quadrant III, both sin and cos are negative. Since tan = sin/cos = (-)/(-), tan is Positive (T in ASTC).',
  },
  {
    id: 's4_q4',
    stage: 4,
    topic: 'quadrants',
    subTopic: 'Quadrant IV cos sign',
    question: 'In Quadrant IV (270° < θ < 360°), which primary trigonometric function is POSITIVE?',
    options: ['Cosine', 'Sine', 'Tangent', 'None'],
    correctAnswer: 'Cosine',
    explanation: 'In Quadrant IV, x > 0 and y < 0, so Cosine is positive while Sine and Tangent are negative (C in ASTC).',
  },
  {
    id: 's4_q5',
    stage: 4,
    topic: 'quadrants',
    subTopic: 'sign evaluation',
    question: 'What is the sign of sin(210°)?',
    options: ['Negative (-)', 'Positive (+)', 'Zero', '1'],
    correctAnswer: 'Negative (-)',
    explanation: '210° lies in Quadrant III, where sine values (y-coordinates) are negative. sin(210°) = -1/2.',
  },

  /* ---------------- STAGE 5: FIND THE ANGLE ---------------- */
  {
    id: 's5_q1',
    stage: 5,
    topic: 'angleFinding',
    subTopic: 'inverse sin acute',
    question: 'If sin(θ) = 1/2 for an acute angle (0° < θ < 90°), what is θ?',
    equation: '\\sin(\\theta) = 1/2 \\implies \\theta = ?',
    options: ['30°', '45°', '60°', '90°'],
    correctAnswer: '30°',
    explanation: 'Since sin(30°) = 1/2, the acute angle θ is 30°.',
  },
  {
    id: 's5_q2',
    stage: 5,
    topic: 'angleFinding',
    subTopic: 'multiple solutions in 0 to 360',
    question: 'For 0° ≤ θ < 360°, where is sin(θ) = 1/2?',
    options: ['30° and 150°', '30° and 330°', '60° and 120°', '45° and 135°'],
    correctAnswer: '30° and 150°',
    explanation: 'Sine is positive in Quadrants I and II. θ = 30° (Quadrant I) and θ = 180° - 30° = 150° (Quadrant II).',
  },
  {
    id: 's5_q3',
    stage: 5,
    topic: 'angleFinding',
    subTopic: 'cos negative solution',
    question: 'If cos(θ) = -1/2, what is the angle θ in Quadrant II?',
    options: ['120°', '150°', '135°', '240°'],
    correctAnswer: '120°',
    explanation: 'Reference angle is 60° (where cos = 1/2). In Quadrant II, θ = 180° - 60° = 120°.',
  },
  {
    id: 's5_q4',
    stage: 5,
    topic: 'angleFinding',
    subTopic: 'tan equal 1',
    question: 'For 0° ≤ θ < 360°, where is tan(θ) = 1?',
    options: ['45° and 225°', '45° and 135°', '45° and 315°', '60° and 240°'],
    correctAnswer: '45° and 225°',
    explanation: 'Tangent is positive in Quadrants I and III. θ = 45° and θ = 180° + 45° = 225°.',
  },
  {
    id: 's5_q5',
    stage: 5,
    topic: 'angleFinding',
    subTopic: 'cos equal zero',
    question: 'For 0° ≤ θ < 360°, for which angles is cos(θ) = 0?',
    options: ['90° and 270°', '0° and 180°', '45° and 225°', '180° and 360°'],
    correctAnswer: '90° and 270°',
    explanation: 'Cosine is zero at the vertical axis intersections: θ = 90° and θ = 270°.',
  },

  /* ---------------- STAGE 6: SPEED ROUND ---------------- */
  {
    id: 's6_q1',
    stage: 6,
    topic: 'sin',
    subTopic: 'rapid sin 0',
    question: 'sin(0°) = ?',
    options: ['0', '1', '1/2', '-1'],
    correctAnswer: '0',
    explanation: 'sin(0°) = 0.',
  },
  {
    id: 's6_q2',
    stage: 6,
    topic: 'cos',
    subTopic: 'rapid cos 90',
    question: 'cos(90°) = ?',
    options: ['0', '1', '√3/2', '1/2'],
    correctAnswer: '0',
    explanation: 'cos(90°) = 0.',
  },
  {
    id: 's6_q3',
    stage: 6,
    topic: 'tan',
    subTopic: 'rapid tan 45',
    question: 'tan(45°) = ?',
    options: ['1', '0', '√3', '√3/3'],
    correctAnswer: '1',
    explanation: 'tan(45°) = 1.',
  },
  {
    id: 's6_q4',
    stage: 6,
    topic: 'sin',
    subTopic: 'rapid sin 60',
    question: 'sin(60°) = ?',
    options: ['√3/2', '1/2', '√2/2', '1'],
    correctAnswer: '√3/2',
    explanation: 'sin(60°) = √3/2.',
  },
  {
    id: 's6_q5',
    stage: 6,
    topic: 'cos',
    subTopic: 'rapid cos 45',
    question: 'cos(45°) = ?',
    options: ['√2/2', '1/2', '√3/2', '0'],
    correctAnswer: '√2/2',
    explanation: 'cos(45°) = √2/2.',
  },
  {
    id: 's6_q6',
    stage: 6,
    topic: 'cos',
    subTopic: 'rapid cos 180',
    question: 'cos(180°) = ?',
    options: ['-1', '0', '1', '-1/2'],
    correctAnswer: '-1',
    explanation: 'cos(180°) = -1.',
  },
  {
    id: 's6_q7',
    stage: 6,
    topic: 'sin',
    subTopic: 'rapid sin 270',
    question: 'sin(270°) = ?',
    options: ['-1', '0', '1', '-√2/2'],
    correctAnswer: '-1',
    explanation: 'sin(270°) = -1.',
  },
  {
    id: 's6_q8',
    stage: 6,
    topic: 'tan',
    subTopic: 'rapid tan 0',
    question: 'tan(0°) = ?',
    options: ['0', '1', 'Undefined', '-1'],
    correctAnswer: '0',
    explanation: 'tan(0°) = 0.',
  },
  {
    id: 's6_q9',
    stage: 6,
    topic: 'sin',
    subTopic: 'rapid sin 45',
    question: 'sin(45°) = ?',
    options: ['√2/2', '1/2', '1', '√3/2'],
    correctAnswer: '√2/2',
    explanation: 'sin(45°) = √2/2.',
  },
  {
    id: 's6_q10',
    stage: 6,
    topic: 'cos',
    subTopic: 'rapid cos 30',
    question: 'cos(30°) = ?',
    options: ['√3/2', '1/2', '√2/2', '1'],
    correctAnswer: '√3/2',
    explanation: 'cos(30°) = √3/2.',
  },

  /* ---------------- STAGE 7: FINAL BOSS BATTLE ---------------- */
  {
    id: 's7_q1',
    stage: 7,
    topic: 'specialAngles',
    subTopic: 'Pythagorean identity',
    question: 'Evaluate: sin²(35°) + cos²(35°)',
    equation: '\\sin^2(35^\\circ) + \\cos^2(35^\\circ) = ?',
    options: ['1', '0', '2', '0.707'],
    correctAnswer: '1',
    explanation: 'Fundamental Pythagorean identity: sin²(θ) + cos²(θ) = 1 for any angle θ.',
  },
  {
    id: 's7_q2',
    stage: 7,
    topic: 'unitCircle',
    subTopic: 'sin 150 value',
    question: 'What is the exact value of sin(150°)?',
    equation: '\\sin(150^\\circ) = ?',
    options: ['1/2', '-1/2', '√3/2', '-√3/2'],
    correctAnswer: '1/2',
    explanation: '150° is in Quadrant II. Reference angle is 30°. In Q II, sin is positive: sin(150°) = sin(30°) = 1/2.',
  },
  {
    id: 's7_q3',
    stage: 7,
    topic: 'quadrants',
    subTopic: 'cos 300 value',
    question: 'What is the exact value of cos(300°)?',
    equation: '\\cos(300^\\circ) = ?',
    options: ['1/2', '-1/2', '√3/2', '-√3/2'],
    correctAnswer: '1/2',
    explanation: '300° is in Quadrant IV (reference angle 60°). In Q IV, cos is positive: cos(300°) = cos(60°) = 1/2.',
  },
  {
    id: 's7_q4',
    stage: 7,
    topic: 'angleFinding',
    subTopic: 'tan negative 1',
    question: 'If tan(θ) = -1 for 0° ≤ θ < 360°, what are the possible angles?',
    options: ['135° and 315°', '45° and 225°', '120° and 300°', '150° and 330°'],
    correctAnswer: '135° and 315°',
    explanation: 'Tangent is negative in Quadrants II and IV. Reference angle 45° gives 180°-45°=135° and 360°-45°=315°.',
  },
  {
    id: 's7_q5',
    stage: 7,
    topic: 'specialAngles',
    subTopic: 'sin 60 times cos 30',
    question: 'Compute: sin(60°) × cos(30°)',
    equation: '\\sin(60^\\circ) \\times \\cos(30^\\circ) = ?',
    options: ['3/4', '1/4', '1/2', '√3/4'],
    correctAnswer: '3/4',
    explanation: 'sin(60°) = √3/2 and cos(30°) = √3/2. Multiplying gives (√3/2) × (√3/2) = 3/4.',
  },
  {
    id: 's7_q6',
    stage: 7,
    topic: 'unitCircle',
    subTopic: 'sin 360 value',
    question: 'What is the value of sin(360°) + cos(360°)?',
    equation: '\\sin(360^\\circ) + \\cos(360^\\circ) = ?',
    options: ['1', '0', '2', '-1'],
    correctAnswer: '1',
    explanation: 'At 360° (full rotation), coordinates are (1, 0). sin(360°) = 0 and cos(360°) = 1, so 0 + 1 = 1.',
  },
];
