apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-standalone
  namespace: acadevia
  labels:
    app: redis
    tier: infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
