CREATE TABLE users (
    id                  BIGINT PRIMARY KEY AUTO_INCREMENT,
    email               VARCHAR(255) UNIQUE NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    role                ENUM('STUDENT', 'TEACHER', 'SCHOOL_ADMIN', 'ADMIN') NOT NULL,
    first_name          VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100) NOT NULL,
    first_name_local    VARCHAR(200),
    last_name_local     VARCHAR(200),
    avatar_url          VARCHAR(500),
    phone               VARCHAR(20),
    class_grade         INT,
    school_id           BIGINT,
    state_id            BIGINT,
    city_id             BIGINT,
    student_school_id   VARCHAR(50),
    preferred_language  VARCHAR(20) DEFAULT 'en',
    board               VARCHAR(50),
    medium              VARCHAR(50),
    total_xp            BIGINT DEFAULT 0,
    current_level       INT DEFAULT 1,
    current_streak      INT DEFAULT 0,
    longest_streak      INT DEFAULT 0,
    wallet_balance      DECIMAL(12,2) DEFAULT 0.00,
    total_credits       INT DEFAULT 0,
    data_saver_mode     BOOLEAN DEFAULT FALSE,
    offline_enabled     BOOLEAN DEFAULT TRUE,
    is_active           BOOLEAN DEFAULT TRUE,
    is_email_verified   BOOLEAN DEFAULT FALSE,
    failed_login_attempts INT DEFAULT 0,
    locked_until        TIMESTAMP NULL,
    last_login_at       TIMESTAMP NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_users_email (email),
    INDEX idx_users_role (role),
    INDEX idx_users_school (school_id),
    INDEX idx_users_state (state_id),
    INDEX idx_users_city (city_id),
    INDEX idx_users_class (class_grade),
    INDEX idx_users_xp (total_xp DESC),
    INDEX idx_users_language (preferred_language),
    INDEX idx_users_student_id (student_school_id),
    INDEX idx_users_active (is_active)
);
