-- V1: Create videos table
CREATE TABLE IF NOT EXISTS videos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    description TEXT,
    video_url VARCHAR(1000),
    video_url_720p VARCHAR(1000),
    video_url_480p VARCHAR(1000),
    video_url_360p VARCHAR(1000),
    thumbnail_url VARCHAR(1000),
    preview_gif_url VARCHAR(1000),
    duration_seconds INT DEFAULT 0,
    duration_formatted VARCHAR(20),
    file_size_mb DECIMAL(10,2),
    file_size_720p_mb DECIMAL(10,2),
    file_size_480p_mb DECIMAL(10,2),
    file_size_360p_mb DECIMAL(10,2),
    encoding_format VARCHAR(50),
    resolution VARCHAR(20),
    frame_rate INT,
    bitrate INT,
    lesson_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    module_id BIGINT,
    instructor_id BIGINT,
    sort_order INT DEFAULT 0,
    is_preview TINYINT(1) DEFAULT 0,
    is_mandatory TINYINT(1) DEFAULT 1,
    is_downloadable TINYINT(1) DEFAULT 0,
    is_active TINYINT(1) DEFAULT 1,
    is_published TINYINT(1) DEFAULT 0,
    is_processing TINYINT(1) DEFAULT 0,
    processing_status VARCHAR(50),
    processing_error TEXT,
    total_views BIGINT DEFAULT 0,
    unique_viewers BIGINT DEFAULT 0,
    total_watch_time_sec BIGINT DEFAULT 0,
    avg_watch_percentage DOUBLE DEFAULT 0.0,
    total_likes INT DEFAULT 0,
    total_dislikes INT DEFAULT 0,
    total_comments INT DEFAULT 0,
    total_bookmarks INT DEFAULT 0,
    total_notes INT DEFAULT 0,
    total_downloads INT DEFAULT 0,
    chapter_markers JSON,
    tags JSON,
    access_level VARCHAR(50) DEFAULT 'ENROLLED',
    language_code VARCHAR(10) DEFAULT 'en',
    transcript TEXT,
    captions_available TINYINT(1) DEFAULT 0,
    published_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,

    INDEX idx_videos_lesson_id (lesson_id),
    INDEX idx_videos_course_id (course_id),
    INDEX idx_videos_module_id (module_id),
    INDEX idx_videos_instructor_id (instructor_id),
    INDEX idx_videos_is_active (is_active),
    INDEX idx_videos_is_published (is_published),
    INDEX idx_videos_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
