-- V2: Create video_pop_questions table
CREATE TABLE IF NOT EXISTS video_pop_questions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    video_id BIGINT NOT NULL,
    timestamp_sec INT NOT NULL,
    question_text TEXT NOT NULL,
    question_type VARCHAR(50) NOT NULL,
    difficulty VARCHAR(20) DEFAULT 'MEDIUM',
    option_a VARCHAR(1000),
    option_b VARCHAR(1000),
    option_c VARCHAR(1000),
    option_d VARCHAR(1000),
    correct_option VARCHAR(10) NOT NULL,
    explanation TEXT,
    hint_text VARCHAR(1000),
    image_url VARCHAR(1000),
    xp_reward INT DEFAULT 10,
    time_limit_sec INT DEFAULT 30,
    is_mandatory TINYINT(1) DEFAULT 0,
    pause_video TINYINT(1) DEFAULT 1,
    allow_skip TINYINT(1) DEFAULT 1,
    max_attempts INT DEFAULT 3,
    is_active TINYINT(1) DEFAULT 1,
    sort_order INT DEFAULT 0,
    topic VARCHAR(255),
    total_attempts INT DEFAULT 0,
    total_correct INT DEFAULT 0,
    accuracy_rate DOUBLE DEFAULT 0.0,
    avg_response_time_sec DOUBLE DEFAULT 0.0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT,

    INDEX idx_pop_questions_video_id (video_id),
    INDEX idx_pop_questions_timestamp (timestamp_sec),
    INDEX idx_pop_questions_type (question_type),
    INDEX idx_pop_questions_difficulty (difficulty),
    INDEX idx_pop_questions_active (is_active),
    CONSTRAINT fk_pop_questions_video FOREIGN KEY (video_id) REFERENCES videos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
