server:
  port: 8087

spring:
  application:
    name: gamification-service
  datasource:
    url: jdbc:mysql://localhost:3306/acadevia_gamification_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
  flyway:
    enabled: false
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gamification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.acadevia.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

acadevia:
  gamification:
    xp-to-credit-ratio: 100
    max-daily-login-xp: 1
    streak-check-timezone: "Asia/Kolkata"
    badge-evaluation-async: true
