apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-standalone
  namespace: acadevia
  labels:
    app: mysql
    tier: infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Gi
