apiVersion: v1
kind: Service
metadata:
  name: leaderboard-service
  namespace: acadevia
spec:
  type: ClusterIP
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
  selector:
    app: leaderboard-service
