import type { AncientChapter, ArchaeologySite } from './types';

export const ANCIENT_CHAPTERS: AncientChapter[] = [
  {
    id: 'chapter1',
    index: 1,
    title: "The King's Road",
    subtitle: 'Chandragupta Maurya & The Crossroads of Magadha',
    heroCharacter: 'Chandragupta Maurya',
    heroRole: 'Founder of the Mauryan Empire',
    avatar: '👑',
    icon: '🏺',
    description: 'Help Chandragupta navigate ancient Indian roads to return home and establish the Mauryan Empire in Magadha.',
    location: 'Ancient Magadha (Pataliputra)',
    era: 'c. 321 BCE — Mauryan Era',
    xpReward: 50,
    learningOutcome: 'Mauryan Empire geography, ancient capitals, and the rise of Magadha.',
  },
  {
    id: 'chapter2',
    index: 2,
    title: "The Traveller's Path",
    subtitle: 'Xuanzang’s Journey to King Harshavardhana',
    heroCharacter: 'Xuanzang',
    heroRole: 'Chinese Buddhist Monk & Scholar',
    avatar: '📜',
    icon: '🧭',
    description: 'Guide the revered scholar Xuanzang on his pilgrimage across 7th-century India to the royal court of King Harshavardhana.',
    location: 'Kannauj & Nalanda',
    era: 'c. 630 CE — Harsha’s Reign',
    xpReward: 50,
    learningOutcome: 'Historical travel accounts, 7th-century Indian kingdoms, and King Harshavardhana.',
  },
  {
    id: 'chapter3',
    index: 3,
    title: 'The Lost Settlements',
    subtitle: 'Neolithic Archaeology Expedition of India',
    heroCharacter: 'Archaeological Team',
    heroRole: 'Field Explorers & Historians',
    avatar: '🔍',
    icon: '⛏️',
    description: 'Explore an interactive map of the Indian subcontinent to excavate 4 foundational Neolithic sites and record findings.',
    location: 'Indian Subcontinent (Kashmir, Balochistan, Tamil Nadu, Bihar)',
    era: 'c. 7000 BCE – 1000 BCE — Neolithic Age',
    xpReward: 50,
    learningOutcome: 'Neolithic settlements, early agriculture, pit houses, and archaeological evidence.',
  },
];

export const NEOLITHIC_SITES: ArchaeologySite[] = [
  {
    id: 'burzahom',
    name: 'Burzahom',
    region: 'Kashmir Valley',
    state: 'Jammu & Kashmir',
    position: { x: 28, y: 18 },
    artefactName: 'Polished Bone Tools & Pit-Dwelling Remnants',
    artefactIcon: '🦴',
    historicalSignificance: 'Famous for underground pit houses dug into soil with steps and polished bone weapons.',
    excavationDepth: 3,
    discovered: false,
  },
  {
    id: 'mehrgarh',
    name: 'Mehrgarh',
    region: 'Bolan Pass / Indus Margin',
    state: 'Balochistan',
    position: { x: 16, y: 34 },
    artefactName: 'Charred Barley Grains & Mud-Brick Granaries',
    artefactIcon: '🌾',
    historicalSignificance: 'One of the earliest known farming and herding sites, showing early wheat/barley cultivation and cattle rearing.',
    excavationDepth: 3,
    discovered: false,
  },
  {
    id: 'chirand',
    name: 'Chirand',
    region: 'Ganges River Basin',
    state: 'Bihar',
    position: { x: 68, y: 44 },
    artefactName: 'Antler Bone Needles & Terracotta Beads',
    artefactIcon: '🏺',
    historicalSignificance: 'Crucial Gangetic Neolithic settlement noted for extraordinary collections of bone tools crafted from deer antlers.',
    excavationDepth: 3,
    discovered: false,
  },
  {
    id: 'paiyampalli',
    name: 'Paiyampalli',
    region: 'Shevaroy Hills / Southern Plateau',
    state: 'Tamil Nadu',
    position: { x: 46, y: 80 },
    artefactName: 'Polished Stone Axes & Millets Evidence',
    artefactIcon: '🪓',
    historicalSignificance: 'Key prehistoric site in South India revealing early millet farming, black-and-red pottery, and stone axe technology.',
    excavationDepth: 3,
    discovered: false,
  },
];
