apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-standalone
  namespace: acadevia
  labels:
    app: minio
    tier: infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 500Gi
