apiVersion: v1
kind: ConfigMap
metadata:
  name: content-service-config
  namespace: acadevia
data:
  SERVER_PORT: "8084"
  DB_NAME: "acadevia_content"
  DB_USER: "acadevia_content_user"
  CONTENT_UPLOAD_MAX_SIZE: "104857600"
  # Bucket names must match those created by minio-init (init-buckets.sh)
  CONTENT_MINIO_BUCKET_VIDEOS: "acadevia-videos"
  CONTENT_MINIO_BUCKET_IMAGES: "acadevia-images"
  CONTENT_MINIO_BUCKET_DOCUMENTS: "acadevia-documents"
  CONTENT_CDN_ENABLED: "true"
