apiVersion: v1
kind: ConfigMap
metadata:
  name: quiz-service-config
  namespace: acadevia
data:
  SERVER_PORT: "8085"
  DB_NAME: "acadevia_quiz"
  DB_USER: "acadevia_quiz_user"
  QUIZ_MAX_QUESTIONS_PER_QUIZ: "200"
  QUIZ_DEFAULT_TIME_LIMIT_SECONDS: "3600"
  QUIZ_RANDOMIZE_DEFAULT: "true"
