package com.acadevia.content.service.impl;

import com.acadevia.content.dto.request.SubtitleCreateRequest;
import com.acadevia.content.dto.request.SubtitleUpdateRequest;
import com.acadevia.content.dto.response.SubtitleResponse;
import com.acadevia.content.entity.VideoSubtitle;
import com.acadevia.content.entity.enums.SubtitleFormat;
import com.acadevia.content.exception.DuplicateResourceException;
import com.acadevia.content.exception.ResourceNotFoundException;
import com.acadevia.content.mapper.SubtitleMapper;
import com.acadevia.content.repository.VideoSubtitleRepository;
import com.acadevia.content.service.SubtitleService;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@RequiredArgsConstructor
public class SubtitleServiceImpl implements SubtitleService {

    private static final Logger log = LoggerFactory.getLogger(SubtitleServiceImpl.class);

    private final VideoSubtitleRepository subtitleRepository;
    private final SubtitleMapper subtitleMapper;

    @Override
    @Transactional
    public SubtitleResponse createSubtitle(SubtitleCreateRequest request) {
        if (Boolean.TRUE.equals(subtitleRepository.existsByVideoIdAndLanguageCode(request.getVideoId(), request.getLanguageCode()))) {
            throw new DuplicateResourceException("Subtitle", "videoId + languageCode",
                    request.getVideoId() + ":" + request.getLanguageCode());
        }

        VideoSubtitle subtitle = subtitleMapper.toEntity(request);
        subtitle.setIsActive(true);

        if (Boolean.TRUE.equals(request.getIsDefault())) {
            subtitleRepository.findByVideoIdAndIsDefaultTrueAndIsActiveTrue(request.getVideoId())
                    .ifPresent(existing -> {
                        existing.setIsDefault(false);
                        subtitleRepository.save(existing);
                    });
        }

        VideoSubtitle saved = subtitleRepository.save(subtitle);
        log.info("Subtitle created: id={}, videoId={}, lang={}", saved.getId(), request.getVideoId(), request.getLanguageCode());
        return subtitleMapper.toResponse(saved);
    }

    @Override
    @Transactional
    public SubtitleResponse updateSubtitle(Long subtitleId, SubtitleUpdateRequest request) {
        VideoSubtitle subtitle = findSubtitleById(subtitleId);

        if (request.getLanguageCode() != null) subtitle.setLanguageCode(request.getLanguageCode());
        if (request.getLanguageName() != null) subtitle.setLanguageName(request.getLanguageName());
        if (request.getSubtitleUrl() != null) subtitle.setSubtitleUrl(request.getSubtitleUrl());
        if (request.getFormat() != null) subtitle.setSubtitleFormat(SubtitleFormat.valueOf(request.getFormat()));
        if (request.getIsAutoGenerated() != null) subtitle.setIsAutoGenerated(request.getIsAutoGenerated());
        if (request.getIsActive() != null) subtitle.setIsActive(request.getIsActive());

        if (Boolean.TRUE.equals(request.getIsDefault())) {
            subtitleRepository.findByVideoIdAndIsDefaultTrueAndIsActiveTrue(subtitle.getVideo().getId())
                    .ifPresent(existing -> {
                        if (!existing.getId().equals(subtitleId)) {
                            existing.setIsDefault(false);
                            subtitleRepository.save(existing);
                        }
                    });
            subtitle.setIsDefault(true);
        } else if (request.getIsDefault() != null) {
            subtitle.setIsDefault(false);
        }

        return subtitleMapper.toResponse(subtitleRepository.save(subtitle));
    }

    @Override
    public List<SubtitleResponse> getSubtitlesByVideoId(Long videoId) {
        return subtitleMapper.toResponseList(subtitleRepository.findByVideoIdAndIsActiveTrue(videoId));
    }

    @Override
    public SubtitleResponse getSubtitleByVideoAndLanguage(Long videoId, String languageCode) {
        VideoSubtitle subtitle = subtitleRepository.findByVideoIdAndLanguageCode(videoId, languageCode)
                .orElseThrow(() -> new ResourceNotFoundException("Subtitle", "videoId:languageCode", videoId + ":" + languageCode));
        return subtitleMapper.toResponse(subtitle);
    }

    @Override
    @Transactional
    public void deleteSubtitle(Long subtitleId) {
        VideoSubtitle subtitle = findSubtitleById(subtitleId);
        subtitle.setIsActive(false);
        subtitleRepository.save(subtitle);
    }

    @Override
    @Transactional
    public void setDefaultSubtitle(Long videoId, Long subtitleId) {
        subtitleRepository.findByVideoIdAndIsDefaultTrueAndIsActiveTrue(videoId)
                .ifPresent(existing -> {
                    if (!existing.getId().equals(subtitleId)) {
                        existing.setIsDefault(false);
                        subtitleRepository.save(existing);
                    }
                });

        VideoSubtitle subtitle = findSubtitleById(subtitleId);
        subtitle.setIsDefault(true);
        subtitleRepository.save(subtitle);
    }

    private VideoSubtitle findSubtitleById(Long subtitleId) {
        return subtitleRepository.findById(subtitleId)
                .orElseThrow(() -> new ResourceNotFoundException("Subtitle", "id", subtitleId));
    }
}
