package com.acadevia.content.entity;

import com.acadevia.content.entity.enums.SubtitleFormat;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

@Entity
@Table(name = "video_subtitles",
    uniqueConstraints = @UniqueConstraint(name = "uk_video_subtitle_lang", columnNames = {"video_id", "language_code"}),
    indexes = {
        @Index(name = "idx_vs_video", columnList = "video_id"),
        @Index(name = "idx_vs_language", columnList = "language_code")
    })
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class VideoSubtitle {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "video_id", nullable = false)
    private Video video;

    @Column(name = "video_id", insertable = false, updatable = false)
    private Long videoId;

    @Column(name = "language_code", length = 20, nullable = false)
    private String languageCode;

    @Column(name = "language_name", length = 100, nullable = false)
    private String languageName;

    @Column(name = "subtitle_url", length = 500, nullable = false)
    private String subtitleUrl;

    @Enumerated(EnumType.STRING)
    @Column(name = "subtitle_format", length = 10)
    @Builder.Default
    private SubtitleFormat subtitleFormat = SubtitleFormat.VTT;

    @Column(name = "is_auto_generated")
    @Builder.Default
    private Boolean isAutoGenerated = false;

    @Column(name = "is_default")
    @Builder.Default
    private Boolean isDefault = false;

    @Column(name = "is_verified")
    @Builder.Default
    private Boolean isVerified = false;

    @Column(name = "is_active")
    @Builder.Default
    private Boolean isActive = true;

    @Column(name = "verified_by")
    private Long verifiedBy;

    @Column(name = "created_by")
    private Long createdBy;

    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}
