apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: acadevia
data:
  SERVER_PORT: "8082"
  DB_NAME: "acadevia_users"
  DB_USER: "acadevia_users_user"
  USER_AVATAR_MAX_SIZE: "5242880"
  USER_PROFILE_CACHE_TTL: "3600"
