apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: acadevia
spec:
  type: ClusterIP
  ports:
    - port: 8092
      targetPort: 8092
      protocol: TCP
  selector:
    app: admin-service
