apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: acadevia
  labels:
    app: analytics-service
    app.kubernetes.io/part-of: acadevia
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8091"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      serviceAccountName: acadevia-sa
      containers:
        - name: analytics-service
          image: acadevia/analytics-service:latest
          ports:
            - containerPort: 8091
          envFrom:
            - configMapRef:
                name: common-config
            - configMapRef:
                name: analytics-service-config
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: acadevia-secrets
                  key: analytics-db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: acadevia-secrets
                  key: jwt-secret
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8091
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8091
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values: ["analytics-service"]
                topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: analytics-service
