apiVersion: v1
kind: ConfigMap
metadata:
  name: game-service-config
  namespace: acadevia
data:
  SERVER_PORT: "8086"
  DB_NAME: "acadevia_game"
  DB_USER: "acadevia_game_user"
  GAME_SESSION_TIMEOUT_SECONDS: "1800"
  GAME_MAX_PLAYERS_PER_SESSION: "50"
