package com.acadevia.content.dto.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SubtitleCreateRequest {

    @NotNull(message = "Video ID is required")
    private Long videoId;

    @NotBlank(message = "Language code is required")
    @Size(max = 10)
    private String languageCode;

    @NotBlank(message = "Language name is required")
    @Size(max = 50)
    private String languageName;

    @NotBlank(message = "Subtitle URL is required")
    @Size(max = 500)
    private String subtitleUrl;

    @Builder.Default
    private String format = "SRT";

    @Builder.Default
    private Boolean isAutoGenerated = false;

    @Builder.Default
    private Boolean isDefault = false;
}
