package com.acadevia.content.dto.request;

import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SubtitleUpdateRequest {

    @Size(max = 10)
    private String languageCode;

    @Size(max = 50)
    private String languageName;

    @Size(max = 500)
    private String subtitleUrl;

    private String format;

    private Boolean isAutoGenerated;

    private Boolean isDefault;

    private Boolean isActive;
}
